"""generate tables

Revision ID: 7c08ed2fb79d
Revises:
Create Date: 2023-11-09 18:29:12.832199

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c08ed2fb79d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from renku_data_services.project.apispec import Visibility

    op.create_table(
        "projects",
        sa.Column("id", sa.String(26), nullable=False),
        sa.Column("name", sa.String(99), nullable=False),
        sa.Column("slug", sa.String(99), nullable=False),
        sa.Column("visibility", sa.Enum(Visibility), nullable=False),
        sa.Column("created_by", sa.String(99), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("repositories", sa.ARRAY(sa.String), nullable=False),
        sa.Column("description", sa.String(5000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="projects",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects", schema="storage")
    # ### end Alembic commands ###
