"""update datetime fields

Revision ID: bcf9e5049127
Revises: 7c08ed2fb79d
Create Date: 2024-03-14 14:48:04.667314

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bcf9e5049127"
down_revision = "7c08ed2fb79d"
branch_labels = None
depends_on = "bfdf48f5ed85"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        column_name="creation_date",
        server_default=sa.text("now()"),
        schema="projects",
    )
    op.add_column(
        "projects",
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        schema="projects",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        column_name="creation_date",
        server_default=None,
        schema="projects",
    )
    op.drop_column("projects", "updated_at", schema="projects")
    # ### end Alembic commands ###
