"""wip: redefine tables

Revision ID: 01180f797019
Revises: 2537a8e1df45
Create Date: 2026-07-15 12:50:59.650960

"""

import sqlalchemy as sa
from alembic import op

from renku_data_services.utils.sqlalchemy import ULIDType

# revision identifiers, used by Alembic.
revision = "01180f797019"
down_revision = "2537a8e1df45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_runs",
        sa.Column("id", ULIDType(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("launch_id", sa.String(), nullable=False),
        sa.Column("launcher_id", ULIDType(), nullable=False),
        sa.Column("submission_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["launcher_id"],
            ["sessions.launchers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.users.keycloak_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="persisted_logs",
    )
    op.create_index(
        op.f("ix_persisted_logs_session_runs_launcher_id"),
        "session_runs",
        ["launcher_id"],
        unique=False,
        schema="persisted_logs",
    )
    op.create_index(
        op.f("ix_persisted_logs_session_runs_user_id"),
        "session_runs",
        ["user_id"],
        unique=False,
        schema="persisted_logs",
    )
    op.create_table(
        "amalthea_session_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", ULIDType(), nullable=False),
        sa.Column("container", sa.String(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("log_line", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["persisted_logs.session_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="persisted_logs",
    )
    op.create_index(
        op.f("ix_persisted_logs_amalthea_session_logs_run_id"),
        "amalthea_session_logs",
        ["run_id"],
        unique=False,
        schema="persisted_logs",
    )
    op.create_index(
        op.f("ix_persisted_logs_amalthea_session_logs_timestamp"),
        "amalthea_session_logs",
        ["timestamp"],
        unique=False,
        schema="persisted_logs",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_persisted_logs_amalthea_session_logs_timestamp"),
        table_name="amalthea_session_logs",
        schema="persisted_logs",
    )
    op.drop_index(
        op.f("ix_persisted_logs_amalthea_session_logs_run_id"),
        table_name="amalthea_session_logs",
        schema="persisted_logs",
    )
    op.drop_table("amalthea_session_logs", schema="persisted_logs")
    op.drop_index(op.f("ix_persisted_logs_session_runs_user_id"), table_name="session_runs", schema="persisted_logs")
    op.drop_index(
        op.f("ix_persisted_logs_session_runs_launcher_id"), table_name="session_runs", schema="persisted_logs"
    )
    op.drop_table("session_runs", schema="persisted_logs")
    # ### end Alembic commands ###
