"""add envidat deposit source

Revision ID: 01k4dy9r2we4
Revises: f2d4841e924b
Create Date: 2026-05-21 11:44:51.439287

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "01k4dy9r2we4"
down_revision = "f2d4841e924b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO storage.deposit_sources (source) VALUES ('envidat') ON CONFLICT DO NOTHING")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM storage.deposit_sources WHERE source = 'envidat'")
    # ### end Alembic commands ###
