"""add dismmiss migration banner user preference

Revision ID: 042eeb50cd8e
Revises: ee719a5fabf6
Create Date: 2025-04-03 08:14:23.416178

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "042eeb50cd8e"
down_revision = "ee719a5fabf6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_preferences", sa.Column("show_project_migration_banner", sa.Boolean(), nullable=False), schema="users"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_preferences", "show_project_migration_banner", schema="users")
    # ### end Alembic commands ###
