"""add idle and hibernation threshold

Revision ID: 04655faf7248
Revises: 43fe05ce19fb
Create Date: 2024-04-25 15:58:58.628860

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04655faf7248"
down_revision = "43fe05ce19fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resource_pools", sa.Column("idle_threshold", sa.Integer(), nullable=True), schema="resource_pools")
    op.add_column(
        "resource_pools", sa.Column("hibernation_threshold", sa.Integer(), nullable=True), schema="resource_pools"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource_pools", "hibernation_threshold", schema="resource_pools")
    op.drop_column("resource_pools", "idle_threshold", schema="resource_pools")
    # ### end Alembic commands ###
