"""add ssh keys

Revision ID: 181e715f787b
Revises: 21c885ddf188
Create Date: 2026-09-14 08:39:12.736593

"""

import sqlalchemy as sa
from alembic import op

from renku_data_services.utils.sqlalchemy import ULIDType  # ### manually edited ###

# revision identifiers, used by Alembic.
revision = "181e715f787b"
down_revision = "21c885ddf188"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ssh_keys",
        sa.Column("id", ULIDType(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("public_key", sa.String(length=2048), nullable=False),
        sa.Column("key_type", sa.String(length=64), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.users.keycloak_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="users",
    )
    op.create_index(op.f("ix_users_ssh_keys_fingerprint"), "ssh_keys", ["fingerprint"], unique=True, schema="users")
    op.create_index(op.f("ix_users_ssh_keys_user_id"), "ssh_keys", ["user_id"], unique=False, schema="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_ssh_keys_user_id"), table_name="ssh_keys", schema="users")
    op.drop_index(op.f("ix_users_ssh_keys_fingerprint"), table_name="ssh_keys", schema="users")
    op.drop_table("ssh_keys", schema="users")
    # ### end Alembic commands ###
