"""create the cluster table

Revision ID: 1d2f64a405aa
Revises: a1f7f5fbec9a
Create Date: 2025-03-12 14:48:19.156390

"""

import sqlalchemy as sa
from alembic import op

from renku_data_services.utils.sqlalchemy import ULIDType

# revision identifiers, used by Alembic.
revision = "1d2f64a405aa"
down_revision = "a1f7f5fbec9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters",
        sa.Column("id", ULIDType(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="resource_pools",
    )
    op.create_index(op.f("ix_resource_pools_clusters_name"), "clusters", ["name"], unique=True, schema="resource_pools")
    op.add_column("resource_pools", sa.Column("cluster_id", ULIDType(), nullable=True), schema="resource_pools")
    op.create_index(
        op.f("ix_resource_pools_resource_pools_cluster_id"),
        "resource_pools",
        ["cluster_id"],
        unique=False,
        schema="resource_pools",
    )
    op.create_foreign_key(
        "resource_pools_resource_pools_cluster_id_fk",
        "resource_pools",
        "clusters",
        ["cluster_id"],
        ["id"],
        source_schema="resource_pools",
        referent_schema="resource_pools",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "resource_pools_resource_pools_cluster_id_fk", "resource_pools", schema="resource_pools", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_resource_pools_resource_pools_cluster_id"), table_name="resource_pools", schema="resource_pools"
    )
    op.drop_column("resource_pools", "cluster_id", schema="resource_pools")
    op.drop_index(op.f("ix_resource_pools_clusters_name"), table_name="clusters", schema="resource_pools")
    op.drop_table("clusters", schema="resource_pools")
    # ### end Alembic commands ###
