"""Add command and args to environment

Revision ID: 1ef98b967767
Revises: 584598f3b769
Create Date: 2024-08-25 21:05:02.158021

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1ef98b967767"
down_revision = "584598f3b769"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "environments",
        sa.Column("args", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True),
        schema="sessions",
    )
    op.add_column(
        "environments",
        sa.Column(
            "command", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        schema="sessions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("environments", "command", schema="sessions")
    op.drop_column("environments", "args", schema="sessions")
    # ### end Alembic commands ###
