"""make tls secret name for remote clusters optional and add default cluster tls cert flag

Revision ID: 287879848fb3
Revises: 9b18adb58e63
Create Date: 2026-01-19 16:07:47.916350

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "287879848fb3"
down_revision = "9b18adb58e63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clusters",
        sa.Column(
            "session_ingress_use_default_cluster_tls_cert",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        schema="resource_pools",
    )
    op.alter_column(
        "clusters",
        "session_tls_secret_name",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
        schema="resource_pools",
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        condition="(session_protocol='https' AND (session_tls_secret_name IS NOT NULL <> session_ingress_use_default_cluster_tls_cert)) "
        "OR session_protocol='http'",
        constraint_name="protocol_tls_secrets",
        table_name="clusters",
        schema="resource_pools",
    )


def downgrade() -> None:
    op.drop_constraint(
        constraint_name="protocol_tls_secrets",
        table_name="clusters",
        schema="resource_pools",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "clusters",
        "session_tls_secret_name",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
        schema="resource_pools",
    )
    op.drop_column("clusters", "session_ingress_use_default_cluster_tls_cert", schema="resource_pools")
    # ### end Alembic commands ###
