"""add remote configuration to resource pools

Revision ID: 29f89d4c00c6
Revises: 5343f6d1ef51
Create Date: 2025-09-17 08:06:47.814885

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "29f89d4c00c6"
down_revision = "5343f6d1ef51"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_pools", sa.Column("remote_provider_id", sa.String(length=99), nullable=True), schema="resource_pools"
    )
    op.add_column(
        "resource_pools",
        sa.Column(
            "remote_configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        schema="resource_pools",
    )
    op.create_index(
        op.f("ix_resource_pools_resource_pools_remote_provider_id"),
        "resource_pools",
        ["remote_provider_id"],
        unique=False,
        schema="resource_pools",
    )
    op.create_foreign_key(
        "resource_pools_remote_provider_id_fk",
        "resource_pools",
        "oauth2_clients",
        ["remote_provider_id"],
        ["id"],
        source_schema="resource_pools",
        referent_schema="connected_services",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "resource_pools_remote_provider_id_fk", "resource_pools", schema="resource_pools", type_="foreignkey"
    )
    op.drop_index(
        op.f("ix_resource_pools_resource_pools_remote_provider_id"),
        table_name="resource_pools",
        schema="resource_pools",
    )
    op.drop_column("resource_pools", "remote_configuration", schema="resource_pools")
    op.drop_column("resource_pools", "remote_provider_id", schema="resource_pools")
    # ### end Alembic commands ###
