"""add project migrations

Revision ID: 32fab117ebec
Revises: d71f0f795d30
Create Date: 2025-02-06 15:20:45.667192

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32fab117ebec"
down_revision = "d71f0f795d30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_migrations",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("project_v1_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "project_v1_id", name="uq_project_migrations"),
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_project_migrations_project_id"),
        "project_migrations",
        ["project_id"],
        unique=False,
        schema="projects",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_project_migrations_project_id"), table_name="project_migrations", schema="projects")
    op.drop_table("project_migrations", schema="projects")
    # ### end Alembic commands ###
