"""add image registry url

Revision ID: 35ea9d8f54e8
Revises: c8061499b966
Create Date: 2025-08-27 14:34:34.190341

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "35ea9d8f54e8"
down_revision = "c8061499b966"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth2_clients", sa.Column("image_registry_url", sa.String(), nullable=True), schema="connected_services"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth2_clients", "image_registry_url", schema="connected_services")
    # ### end Alembic commands ###
