"""remove renku v1 storage

Revision ID: 36435401b2e7
Revises: 01k4dy9r2we4
Create Date: 2026-07-30 06:04:05.053191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36435401b2e7'
down_revision = '01k4dy9r2we4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_storage_cloud_storage_project_id', table_name='cloud_storage', schema='storage')
    op.drop_table('cloud_storage', schema='storage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_storage',
    sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('source_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('storage_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
    sa.Column('readonly', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('storage_id', name='cloud_storage_pkey'),
    sa.UniqueConstraint('project_id', 'name', name='_unique_name_uc'),
    schema='storage'
    )
    op.create_index('ix_storage_cloud_storage_project_id', 'cloud_storage', ['project_id'], unique=False, schema='storage')
    # ### end Alembic commands ###
