"""squashme: add connected services

Revision ID: 459051002ffe
Revises: 1dd7c321f126
Create Date: 2024-04-23 07:27:13.698930

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '459051002ffe'
down_revision = '1dd7c321f126'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth2_connections',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(length=99), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('cookie', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'connected', name='connectionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['connected_services.oauth2_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='connected_services'
    )
    op.create_index(op.f('ix_connected_services_oauth2_connections_client_id'), 'oauth2_connections', ['client_id'], unique=False, schema='connected_services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from renku_data_services.connected_services.orm import ConnectionStatus

    op.drop_index(op.f('ix_connected_services_oauth2_connections_client_id'), table_name='oauth2_connections', schema='connected_services')
    op.drop_table('oauth2_connections', schema='connected_services')
    sa.Enum(ConnectionStatus).drop(op.get_bind())
    # ### end Alembic commands ###
