"""add secret expiration timestamp

Revision ID: 45d8d3ae5fdd
Revises: 21fd67938150
Create Date: 2025-12-04 13:32:00.263461

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45d8d3ae5fdd"
down_revision = "21fd67938150"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "secrets", sa.Column("expiration_timestamp", sa.DateTime(timezone=True), nullable=True), schema="secrets"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("secrets", "expiration_timestamp", schema="secrets")
    # ### end Alembic commands ###
