"""fix user preferences sequence

Revision ID: 46236d8d7cbe
Revises: 726d5d0e1f28
Create Date: 2024-10-15 07:42:08.683052

"""

from alembic import op
from psycopg import sql

# revision identifiers, used by Alembic.
revision = "46236d8d7cbe"
down_revision = "726d5d0e1f28"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    statement = sql.SQL("SELECT MAX(id) FROM users.user_preferences").as_string(connection)  # type: ignore[arg-type]
    res = connection.exec_driver_sql(statement)
    row = res.fetchone()
    if row is not None and len(row) > 0 and row[0] is not None:
        last_id = row[0]
        sql_string = f"ALTER SEQUENCE users.user_preferences_id_seq  RESTART WITH {last_id+1}"
        statement = sql.SQL(sql_string).as_string(connection)  # type: ignore[arg-type]
        connection.exec_driver_sql(statement)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
