"""squashme: add connected services

Revision ID: 4745ab6414ad
Revises: fe0f6279d19d
Create Date: 2024-05-03 10:46:55.857151

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4745ab6414ad'
down_revision = 'fe0f6279d19d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth2_clients', 'kind',
               existing_type=postgresql.ENUM('gitlab', 'github', name='providerkind'),
               nullable=False,
               schema='connected_services')
    op.alter_column('oauth2_clients', 'scope',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='connected_services')
    op.alter_column('oauth2_clients', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='connected_services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth2_clients', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='connected_services')
    op.alter_column('oauth2_clients', 'scope',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='connected_services')
    op.alter_column('oauth2_clients', 'kind',
               existing_type=postgresql.ENUM('gitlab', 'github', name='providerkind'),
               nullable=True,
               schema='connected_services')
    # ### end Alembic commands ###
