"""feat: add support for remote sessions

Revision ID: 5343f6d1ef51
Revises: c8061499b966
Create Date: 2025-08-25 07:20:38.910509

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5343f6d1ef51"
down_revision = "c8061499b966"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_pools",
        sa.Column("remote", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        schema="resource_pools",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource_pools", "remote", schema="resource_pools")
    # ### end Alembic commands ###
