"""Update session secrets

Revision ID: 5dadcae4e4c3
Revises: 6ae750a5d636
Create Date: 2024-11-06 14:35:58.708804

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5dadcae4e4c3"
down_revision = "6ae750a5d636"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launcher_secrets",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("secret_slot_id", sa.String(length=26), nullable=False),
        sa.Column("secret_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(["secret_id"], ["secrets.secrets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["secret_slot_id"], ["sessions.launcher_secret_slots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.users.keycloak_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_slot_id", "user_id", name="_unique_secret_slot_id_user_id"),
        schema="sessions",
    )
    op.create_index(
        op.f("ix_sessions_launcher_secrets_user_id"), "launcher_secrets", ["user_id"], unique=False, schema="sessions"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_launcher_secrets_user_id"), table_name="launcher_secrets", schema="sessions")
    op.drop_table("launcher_secrets", schema="sessions")
    # ### end Alembic commands ###
