"""create tables for deposits

Revision ID: 68d751fb3525
Revises: 53ef858f34ea
Create Date: 2026-02-22 19:57:59.709938

"""

import sqlalchemy as sa
from alembic import op

from renku_data_services.utils.sqlalchemy import ULIDType

# revision identifiers, used by Alembic.
revision = "68d751fb3525"
down_revision = "53ef858f34ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deposit_sources",
        sa.Column(
            "id",
            ULIDType(),
            server_default=sa.text("generate_ulid()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="storage",
    )
    op.create_index(
        op.f("ix_storage_deposit_sources_source"), "deposit_sources", ["source"], unique=True, schema="storage"
    )
    op.create_table(
        "deposit_statuses",
        sa.Column(
            "id",
            ULIDType(),
            server_default=sa.text("generate_ulid()"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="storage",
    )
    op.create_index(
        op.f("ix_storage_deposit_statuses_status"), "deposit_statuses", ["status"], unique=True, schema="storage"
    )
    op.create_table(
        "deposits",
        sa.Column(
            "id",
            ULIDType(),
            server_default=sa.text("generate_ulid()"),
            nullable=False,
        ),
        sa.Column("source_id", ULIDType(), nullable=False),
        sa.Column("status_id", ULIDType(), nullable=False),
        sa.Column("original_id", sa.String(), nullable=False),
        sa.Column("data_connector_id", ULIDType(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.String(), nullable=True),
        sa.Column("job_name", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cluster_id", ULIDType(), nullable=True),
        sa.ForeignKeyConstraint(["cluster_id"], ["resource_pools.clusters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["data_connector_id"], ["storage.data_connectors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["storage.deposit_sources.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["status_id"], ["storage.deposit_statuses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.users.keycloak_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "user_id"),
        schema="storage",
    )
    op.create_index(op.f("ix_storage_deposits_cluster_id"), "deposits", ["cluster_id"], unique=False, schema="storage")
    op.create_index(
        op.f("ix_storage_deposits_data_connector_id"), "deposits", ["data_connector_id"], unique=False, schema="storage"
    )
    op.create_index(op.f("ix_storage_deposits_source_id"), "deposits", ["source_id"], unique=False, schema="storage")
    op.create_index(op.f("ix_storage_deposits_status_id"), "deposits", ["status_id"], unique=False, schema="storage")
    # ### end Alembic commands ###
    op.execute("INSERT INTO storage.deposit_statuses (status) VALUES ('in_progress'), ('complete')")
    op.execute("INSERT INTO storage.deposit_sources (source) VALUES ('zenodo')")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_deposits_status_id"), table_name="deposits", schema="storage")
    op.drop_index(op.f("ix_storage_deposits_source_id"), table_name="deposits", schema="storage")
    op.drop_index(op.f("ix_storage_deposits_data_connector_id"), table_name="deposits", schema="storage")
    op.drop_index(op.f("ix_storage_deposits_cluster_id"), table_name="deposits", schema="storage")
    op.drop_table("deposits", schema="storage")
    op.drop_index(op.f("ix_storage_deposit_statuses_status"), table_name="deposit_statuses", schema="storage")
    op.drop_table("deposit_statuses", schema="storage")
    op.drop_index(op.f("ix_storage_deposit_sources_source"), table_name="deposit_sources", schema="storage")
    op.drop_table("deposit_sources", schema="storage")
    # ### end Alembic commands ###
