"""Add session secrets

Revision ID: 6ae750a5d636
Revises: 1ef98b967767
Create Date: 2024-11-06 10:23:53.874655

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ae750a5d636"
down_revision = "1ef98b967767"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launcher_secret_slots",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("session_launcher_id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=99), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.users.keycloak_id"],
        ),
        sa.ForeignKeyConstraint(["session_launcher_id"], ["sessions.launchers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_launcher_id", "filename", name="_unique_session_launcher_id_filename"),
        schema="sessions",
    )
    op.create_index(
        op.f("ix_sessions_launcher_secret_slots_created_by_id"),
        "launcher_secret_slots",
        ["created_by_id"],
        unique=False,
        schema="sessions",
    )
    op.create_index(
        op.f("ix_sessions_launcher_secret_slots_session_launcher_id"),
        "launcher_secret_slots",
        ["session_launcher_id"],
        unique=False,
        schema="sessions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sessions_launcher_secret_slots_session_launcher_id"),
        table_name="launcher_secret_slots",
        schema="sessions",
    )
    op.drop_index(
        op.f("ix_sessions_launcher_secret_slots_created_by_id"), table_name="launcher_secret_slots", schema="sessions"
    )
    op.drop_table("launcher_secret_slots", schema="sessions")
    # ### end Alembic commands ###
