"""fake: add column to users table

Revision ID: 6f4b0cefd73d
Revises: 4cbb36ac2a5c
Create Date: 2026-01-13 08:25:50.413195

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f4b0cefd73d"
down_revision = "4cbb36ac2a5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("example", sa.String(), nullable=True), schema="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "example", schema="users")
    # ### end Alembic commands ###
