"""Add builds

Revision ID: 71ef5efe740f
Revises: 1e296d744eac
Create Date: 2025-02-07 14:33:31.895125

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "71ef5efe740f"
down_revision = "1e296d744eac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE buildstatus") # TODO: temporary fix for this PR
    op.create_table(
        "builds",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("environment_id", sa.String(length=26), nullable=False),
        sa.Column(
            "status", sa.Enum("in_progress", "failed", "cancelled", "succeeded", name="buildstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_image", sa.String(length=500), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_repository_url", sa.String(length=500), nullable=True),
        sa.Column("result_repository_git_commit_sha", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["environment_id"], ["sessions.environments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="sessions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("builds", schema="sessions")
    op.execute("DROP TYPE buildstatus")
    # ### end Alembic commands ###
