"""add secret expiration timestamp

Revision ID: 780302876bce
Revises: 21fd67938150
Create Date: 2025-12-10 09:12:40.827447

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "780302876bce"
down_revision = "21fd67938150"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "secrets", sa.Column("expiration_timestamp", sa.DateTime(timezone=True), nullable=True), schema="secrets"
    )
    op.create_index(
        op.f("ix_secrets_secrets_expiration_timestamp"),
        "secrets",
        ["expiration_timestamp"],
        unique=False,
        schema="secrets",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_secrets_secrets_expiration_timestamp"), table_name="secrets", schema="secrets")
    op.drop_column("secrets", "expiration_timestamp", schema="secrets")
    # ### end Alembic commands ###
