"""add_secret_expiration_timestamp

Revision ID: 7bc32829ed2f
Revises: 9058bf0a1a12
Create Date: 2024-08-21 12:38:30.932694

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7bc32829ed2f"
down_revision = "9058bf0a1a12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "secrets", sa.Column("expiration_timestamp", sa.DateTime(timezone=True), nullable=True), schema="secrets"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("secrets", "expiration_timestamp", schema="secrets")
    # ### end Alembic commands ###
