"""add capacity reservation tables

Revision ID: 8018136972d4
Revises: 287879848fb3
Create Date: 2026-02-12 13:57:23.099601

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from renku_data_services.utils.sqlalchemy import ULIDType

# revision identifiers, used by Alembic.
revision = "8018136972d4"
down_revision = "287879848fb3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capacity_reservations",
        sa.Column("id", ULIDType(), server_default=sa.text("generate_ulid()"), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column(
            "recurrence", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "provisioning",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "matching", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="capacity_reservation",
    )
    op.create_index(
        op.f("ix_capacity_reservation_capacity_reservations_name"),
        "capacity_reservations",
        ["name"],
        unique=False,
        schema="capacity_reservation",
    )
    op.create_table(
        "occurrences",
        sa.Column("id", ULIDType(), server_default=sa.text("generate_ulid()"), nullable=False),
        sa.Column("reservation_id", ULIDType(), nullable=False),
        sa.Column("activate_at_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "ACTIVE", "COMPLETED", name="occurrence_state"), nullable=False),
        sa.Column("deployment_name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["reservation_id"], ["capacity_reservation.capacity_reservations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="capacity_reservation",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("occurrences", schema="capacity_reservation")
    op.drop_index(
        op.f("ix_capacity_reservation_capacity_reservations_name"),
        table_name="capacity_reservations",
        schema="capacity_reservation",
    )
    op.drop_table("capacity_reservations", schema="capacity_reservation")
    # ### end Alembic commands ###
