"""Protect launcher associations

Revision ID: 807a50890bf8
Revises: fc1a97661d0c
Create Date: 2026-10-01 15:35:13.648727

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import renku_data_services.utils.sqlalchemy

# revision identifiers, used by Alembic.
revision = "807a50890bf8"
down_revision = "fc1a97661d0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launcher_data_connectors",
        sa.Column("launcher_id", renku_data_services.utils.sqlalchemy.ULIDType(), nullable=False),
        sa.Column("data_connector_to_project_link_id", renku_data_services.utils.sqlalchemy.ULIDType(), nullable=False),
        sa.Column("policy", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_connector_to_project_link_id"], ["storage.data_connector_to_project_links.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["launcher_id"], ["sessions.launchers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("launcher_id", "data_connector_to_project_link_id"),
        schema="sessions",
    )
    op.create_table(
        "launcher_repositories",
        sa.Column("launcher_id", renku_data_services.utils.sqlalchemy.ULIDType(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column(
            "policy", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(["launcher_id"], ["sessions.launchers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["projects.projects_repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("launcher_id", "repository_id"),
        schema="sessions",
    )
    op.create_unique_constraint(
        "_unique_session_secret_slot_id_project_id", "session_secret_slots", ["id", "project_id"], schema="projects"
    )
    op.create_unique_constraint("_unique_launcher_id_project_id", "launchers", ["id", "project_id"], schema="sessions")
    op.create_table(
        "launcher_secrets",
        sa.Column("launcher_id", renku_data_services.utils.sqlalchemy.ULIDType(), nullable=False),
        sa.Column("secret_slot_id", renku_data_services.utils.sqlalchemy.ULIDType(), nullable=False),
        sa.Column("project_id", renku_data_services.utils.sqlalchemy.ULIDType(), nullable=False),
        sa.Column("policy", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["launcher_id", "project_id"],
            ["sessions.launchers.id", "sessions.launchers.project_id"],
            name="_fk_launcher_secrets_launcher",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["secret_slot_id", "project_id"],
            ["projects.session_secret_slots.id", "projects.session_secret_slots.project_id"],
            name="_fk_launcher_secrets_secret_slot",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("launcher_id", "secret_slot_id"),
        schema="sessions",
    )
    op.create_index(
        op.f("ix_sessions_launcher_secrets_project_id"),
        "launcher_secrets",
        ["project_id"],
        unique=False,
        schema="sessions",
    )
    op.create_index(
        op.f("ix_sessions_launcher_secrets_secret_slot_id"),
        "launcher_secrets",
        ["secret_slot_id"],
        unique=False,
        schema="sessions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_launcher_secrets_secret_slot_id"), table_name="launcher_secrets", schema="sessions")
    op.drop_index(op.f("ix_sessions_launcher_secrets_project_id"), table_name="launcher_secrets", schema="sessions")
    op.drop_table("launcher_secrets", schema="sessions")
    op.drop_table("launcher_repositories", schema="sessions")
    op.drop_table("launcher_data_connectors", schema="sessions")
    op.drop_constraint("_unique_launcher_id_project_id", "launchers", schema="sessions", type_="unique")
    op.drop_constraint(
        "_unique_session_secret_slot_id_project_id", "session_secret_slots", schema="projects", type_="unique"
    )
    # ### end Alembic commands ###
