"""Add keywords to projects table

Revision ID: 85447af3d0dd
Revises:
Create Date: 2024-04-10 11:16:11.667190

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85447af3d0dd"
down_revision = "7c08ed2fb79d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("keywords", sa.ARRAY(sa.String(99))), schema="projects")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "keywords", schema="projects")
    # ### end Alembic commands ###
