"""create namespace tables

Revision ID: 87a439f35346
Revises: fd2117d2be29
Create Date: 2024-03-27 14:10:49.194395

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "87a439f35346"
down_revision = "fd2117d2be29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sa.String(length=99), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.users.keycloak_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="common",
    )
    op.create_index(op.f("ix_common_groups_created_by"), "groups", ["created_by"], unique=False, schema="common")
    op.create_index(op.f("ix_common_groups_name"), "groups", ["name"], unique=False, schema="common")
    op.create_table(
        "group_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["common.groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.users.keycloak_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="common",
    )
    op.create_index(
        op.f("ix_common_group_members_group_id"), "group_members", ["group_id"], unique=False, schema="common"
    )
    op.create_table(
        "namespaces",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("slug", sa.String(length=99), nullable=False),
        sa.Column("group_id", sa.String(length=26), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint("(user_id IS NULL) <> (group_id IS NULL)", name="either_group_id_or_user_id_is_set"),
        sa.ForeignKeyConstraint(["group_id"], ["common.groups.id"], name="namespaces_group_id_fk", ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.users.keycloak_id"], name="namespaces_user_keycloak_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="common",
    )
    op.create_index(op.f("ix_common_namespaces_group_id"), "namespaces", ["group_id"], unique=False, schema="common")
    op.create_index(op.f("ix_common_namespaces_slug"), "namespaces", ["slug"], unique=True, schema="common")
    op.create_index(op.f("ix_common_namespaces_user_id"), "namespaces", ["user_id"], unique=False, schema="common")
    op.create_table(
        "namespaces_old",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("slug", sa.String(length=99), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("latest_slug_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(["latest_slug_id"], ["common.namespaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="common",
    )
    op.create_index(
        op.f("ix_common_namespaces_old_created_at"), "namespaces_old", ["created_at"], unique=False, schema="common"
    )
    op.create_index(
        op.f("ix_common_namespaces_old_latest_slug_id"),
        "namespaces_old",
        ["latest_slug_id"],
        unique=False,
        schema="common",
    )
    op.create_index(op.f("ix_common_namespaces_old_slug"), "namespaces_old", ["slug"], unique=False, schema="common")
    op.create_table(
        "project_slugs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=99), nullable=False),
        sa.Column("project_id", sa.String(length=26), nullable=False),
        sa.Column("namespace_id", sa.String(length=26), nullable=False),
        sa.ForeignKeyConstraint(
            ["namespace_id"], ["common.namespaces.id"], name="project_slugs_namespace_id_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.projects.id"], name="project_slugs_project_id_fk", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_project_slugs_namespace_id"),
        "project_slugs",
        ["namespace_id"],
        unique=False,
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_project_slugs_project_id"), "project_slugs", ["project_id"], unique=False, schema="projects"
    )
    op.create_index(op.f("ix_projects_project_slugs_slug"), "project_slugs", ["slug"], unique=False, schema="projects")
    op.create_index(
        "project_slugs_unique_slugs", "project_slugs", ["namespace_id", "slug"], unique=True, schema="projects"
    )
    op.create_table(
        "project_slugs_old",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=99), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("latest_slug_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["latest_slug_id"], ["projects.project_slugs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_project_slugs_old_created_at"),
        "project_slugs_old",
        ["created_at"],
        unique=False,
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_project_slugs_old_latest_slug_id"),
        "project_slugs_old",
        ["latest_slug_id"],
        unique=False,
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_project_slugs_old_slug"), "project_slugs_old", ["slug"], unique=False, schema="projects"
    )
    op.drop_column("projects", "slug", schema="projects")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("slug", sa.VARCHAR(length=99), autoincrement=False, nullable=True), schema="projects"
    )
    op.execute(
        "MERGE INTO projects.projects pr USING projects.project_slugs sl "
        "ON pr.id = sl.project_id WHEN MATCHED THEN UPDATE SET slug = sl.slug"
    )
    op.alter_column("projects", "slug", schema="projects", nullable=False)

    op.drop_index(op.f("ix_common_namespaces_old_slug"), table_name="namespaces_old", schema="common")
    op.drop_index(op.f("ix_common_namespaces_old_latest_slug_id"), table_name="namespaces_old", schema="common")
    op.drop_index(op.f("ix_common_namespaces_old_created_at"), table_name="namespaces_old", schema="common")
    op.drop_index(op.f("ix_common_namespaces_user_id"), table_name="namespaces", schema="common")
    op.drop_index(op.f("ix_common_namespaces_slug"), table_name="namespaces", schema="common")
    op.drop_index(op.f("ix_common_namespaces_group_id"), table_name="namespaces", schema="common")
    op.drop_index(op.f("ix_common_group_members_group_id"), table_name="group_members", schema="common")
    op.drop_index(op.f("ix_common_groups_name"), table_name="groups", schema="common")
    op.drop_index(op.f("ix_common_groups_created_by"), table_name="groups", schema="common")
    op.drop_index(op.f("ix_projects_project_slugs_old_slug"), table_name="project_slugs_old", schema="projects")
    op.drop_index(
        op.f("ix_projects_project_slugs_old_latest_slug_id"), table_name="project_slugs_old", schema="projects"
    )
    op.drop_index(op.f("ix_projects_project_slugs_old_created_at"), table_name="project_slugs_old", schema="projects")
    op.drop_index("project_slugs_unique_slugs", table_name="project_slugs", schema="projects")
    op.drop_index(op.f("ix_projects_project_slugs_slug"), table_name="project_slugs", schema="projects")
    op.drop_index(op.f("ix_projects_project_slugs_project_id"), table_name="project_slugs", schema="projects")
    op.drop_index(op.f("ix_projects_project_slugs_namespace_id"), table_name="project_slugs", schema="projects")
    op.drop_table("group_members", schema="common")
    op.drop_table("project_slugs_old", schema="projects")
    op.drop_table("project_slugs", schema="projects")
    op.drop_table("namespaces_old", schema="common")
    op.drop_table("namespaces", schema="common")
    op.drop_table("groups", schema="common")
    # ### end Alembic commands ###
