"""create k8s cache tables

Revision ID: 8c7d2738fd9e
Revises: a1f7f5fbec9a
Create Date: 2025-04-02 07:47:42.745569

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8c7d2738fd9e"
down_revision = "a1f7f5fbec9a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "k8s_objects",
        sa.Column("id", sa.String(26), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "manifest",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean()),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("kind", sa.String()),
        sa.Column("cluster", sa.String()),
        sa.PrimaryKeyConstraint("id"),
        schema="common",
    )
    op.create_index(op.f("ix_k8s_objects_cluster"), "k8s_objects", ["cluster"], unique=False, schema="common")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_k8s_objects_cluster"), table_name="k8s_objects", schema="common")
    op.drop_table("k8s_objects", schema="common")
    # ### end Alembic commands ###
