"""add secret expiration timestamp

Revision ID: 998a5b8cb4f2
Revises: d1cdcbb2adc3
Create Date: 2025-01-09 16:05:17.299531

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "998a5b8cb4f2"
down_revision = "d1cdcbb2adc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "secrets", sa.Column("expiration_timestamp", sa.DateTime(timezone=True), nullable=True), schema="secrets"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("secrets", "expiration_timestamp", schema="secrets")
    # ### end Alembic commands ###
