"""add timestamp to events

Revision ID: a44d23460eff
Revises: bfdf48f5ed85
Create Date: 2024-03-18 14:09:34.303672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a44d23460eff"
down_revision = "bfdf48f5ed85"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("timestamp", sa.DateTime(), nullable=False), schema="events")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "timestamp", schema="events")
    # ### end Alembic commands ###
