"""add secret expiration timestamp

Revision ID: aa8f1a39a3bc
Revises: d437be68a4fb
Create Date: 2025-10-21 13:12:56.882429

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aa8f1a39a3bc"
down_revision = "d437be68a4fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "secrets", sa.Column("expiration_timestamp", sa.DateTime(timezone=True), nullable=True), schema="secrets"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("secrets", "expiration_timestamp", schema="secrets")
    # ### end Alembic commands ###
