"""Add launcher associations

Revision ID: b13341233c80
Revises: fc1a97661d0c
Create Date: 2026-09-19 09:26:48.447257

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from renku_data_services.utils.sqlalchemy import ULIDType

# revision identifiers, used by Alembic.
revision = "b13341233c80"
down_revision = "fc1a97661d0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "launcher_data_connectors",
        sa.Column("launcher_id", ULIDType(), nullable=False),
        sa.Column("data_connector_to_project_link_id", ULIDType(), nullable=False),
        sa.Column(
            "policy", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["data_connector_to_project_link_id"], ["storage.data_connector_to_project_links.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["launcher_id"], ["sessions.launchers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("launcher_id", "data_connector_to_project_link_id"),
        schema="sessions",
    )
    op.create_table(
        "launcher_repositories",
        sa.Column("launcher_id", ULIDType(), nullable=False),
        sa.Column("repository_id", sa.Integer(), nullable=False),
        sa.Column(
            "policy", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(["launcher_id"], ["sessions.launchers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["repository_id"], ["projects.projects_repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("launcher_id", "repository_id"),
        schema="sessions",
    )
    op.create_table(
        "launcher_secrets",
        sa.Column("launcher_id", ULIDType(), nullable=False),
        sa.Column("secret_slot_id", ULIDType(), nullable=False),
        sa.Column(
            "policy", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(["launcher_id"], ["sessions.launchers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["secret_slot_id"], ["projects.session_secret_slots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("launcher_id", "secret_slot_id"),
        schema="sessions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("launcher_secrets", schema="sessions")
    op.drop_table("launcher_repositories", schema="sessions")
    op.drop_table("launcher_data_connectors", schema="sessions")
    # ### end Alembic commands ###
