"""Add ingress parameters for remote clusters

Revision ID: b402b9d584bf
Revises: f4ad62b7b323
Create Date: 2025-06-20 11:05:22.238236

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b402b9d584bf"
down_revision = "f4ad62b7b323"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clusters", sa.Column("session_protocol", sa.String(length=10), nullable=False), schema="resource_pools"
    )
    op.add_column("clusters", sa.Column("session_host", sa.String(length=256), nullable=False), schema="resource_pools")
    op.add_column("clusters", sa.Column("session_port", sa.Integer(), nullable=False), schema="resource_pools")
    op.add_column("clusters", sa.Column("session_path", sa.String(length=40), nullable=False), schema="resource_pools")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clusters", "session_path", schema="resource_pools")
    op.drop_column("clusters", "session_port", schema="resource_pools")
    op.drop_column("clusters", "session_host", schema="resource_pools")
    op.drop_column("clusters", "session_protocol", schema="resource_pools")
    # ### end Alembic commands ###
