"""add doi and publisher info for global data connectors

Revision ID: bd97866a6253
Revises: 780302876bce
Create Date: 2025-12-03 09:38:17.534403

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd97866a6253"
down_revision = "780302876bce"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_connectors", sa.Column("doi", sa.String(), nullable=True), schema="storage")
    op.add_column("data_connectors", sa.Column("publisher_name", sa.String(), nullable=True), schema="storage")
    op.add_column("data_connectors", sa.Column("publisher_url", sa.String(), nullable=True), schema="storage")
    op.create_index(op.f("ix_storage_data_connectors_doi"), "data_connectors", ["doi"], unique=False, schema="storage")
    op.create_index(
        op.f("ix_storage_data_connectors_publisher_name"),
        "data_connectors",
        ["publisher_name"],
        unique=False,
        schema="storage",
    )
    op.create_index(
        op.f("ix_storage_data_connectors_publisher_url"),
        "data_connectors",
        ["publisher_url"],
        unique=False,
        schema="storage",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_data_connectors_publisher_url"), table_name="data_connectors", schema="storage")
    op.drop_index(op.f("ix_storage_data_connectors_publisher_name"), table_name="data_connectors", schema="storage")
    op.drop_index(op.f("ix_storage_data_connectors_doi"), table_name="data_connectors", schema="storage")
    op.drop_column("data_connectors", "publisher_url", schema="storage")
    op.drop_column("data_connectors", "publisher_name", schema="storage")
    op.drop_column("data_connectors", "doi", schema="storage")
    # ### end Alembic commands ###
