"""update connected services tables

* Add use_pkce to oauth2_clients
* Add code_verifier and next_url to oauth2_connections

Revision ID: c0631477aea4
Revises: f34b87ddd954
Create Date: 2024-05-29 07:51:40.330164

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0631477aea4"
down_revision = "f34b87ddd954"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth2_clients",
        sa.Column("use_pkce", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        schema="connected_services",
    )
    op.add_column(
        "oauth2_connections", sa.Column("code_verifier", sa.String(), nullable=True), schema="connected_services"
    )
    op.add_column("oauth2_connections", sa.Column("next_url", sa.String(), nullable=True), schema="connected_services")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth2_connections", "next_url", schema="connected_services")
    op.drop_column("oauth2_connections", "code_verifier", schema="connected_services")
    op.drop_column("oauth2_clients", "use_pkce", schema="connected_services")
    # ### end Alembic commands ###
