"""add extra indices to resource request log

Revision ID: c29f65247e88
Revises: d785165cf8cd
Create Date: 2026-05-13 09:48:19.941537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29f65247e88'
down_revision = 'd785165cf8cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resource_pools_resource_requests_log_phase'), 'resource_requests_log', ['phase'], unique=False, schema='resource_pools')
    op.create_index(op.f('ix_resource_pools_resource_requests_log_project_id'), 'resource_requests_log', ['project_id'], unique=False, schema='resource_pools')
    op.create_index(op.f('ix_resource_pools_resource_requests_log_resource_class_id'), 'resource_requests_log', ['resource_class_id'], unique=False, schema='resource_pools')
    op.create_index(op.f('ix_resource_pools_resource_requests_log_resource_pool_id'), 'resource_requests_log', ['resource_pool_id'], unique=False, schema='resource_pools')
    op.create_index(op.f('ix_resource_pools_resource_requests_log_user_id'), 'resource_requests_log', ['user_id'], unique=False, schema='resource_pools')
    op.create_index('ix_uid_phase', 'resource_requests_log', ['uid', 'phase'], unique=False, schema='resource_pools')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_uid_phase', table_name='resource_requests_log', schema='resource_pools')
    op.drop_index(op.f('ix_resource_pools_resource_requests_log_user_id'), table_name='resource_requests_log', schema='resource_pools')
    op.drop_index(op.f('ix_resource_pools_resource_requests_log_resource_pool_id'), table_name='resource_requests_log', schema='resource_pools')
    op.drop_index(op.f('ix_resource_pools_resource_requests_log_resource_class_id'), table_name='resource_requests_log', schema='resource_pools')
    op.drop_index(op.f('ix_resource_pools_resource_requests_log_project_id'), table_name='resource_requests_log', schema='resource_pools')
    op.drop_index(op.f('ix_resource_pools_resource_requests_log_phase'), table_name='resource_requests_log', schema='resource_pools')
    # ### end Alembic commands ###
