"""add service account name to cluster

Revision ID: ca3731b65787
Revises: cfda91a3a6a6
Create Date: 2025-07-07 13:25:48.254099

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca3731b65787"
down_revision = "cfda91a3a6a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clusters", sa.Column("service_account_name", sa.String(length=256), nullable=True), schema="resource_pools"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clusters", "service_account_name", schema="resource_pools")
    # ### end Alembic commands ###
