"""make group a separate field

Revision ID: dcb9648c3c15
Revises: 042eeb50cd8e
Create Date: 2025-05-13 01:16:39.076648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb9648c3c15'
down_revision = '042eeb50cd8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('k8s_objects', sa.Column('group', sa.String(), nullable=True), schema='common')
    op.create_index(op.f('ix_common_k8s_objects_group'), 'k8s_objects', ['group'], unique=False, schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_k8s_objects_group'), table_name='k8s_objects', schema='common')
    op.drop_column('k8s_objects', 'group', schema='common')
    # ### end Alembic commands ###
