"""add strip prefix option to environments

Revision ID: e117405fed51
Revises: ca3731b65787
Create Date: 2025-03-27 16:48:51.460749

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e117405fed51"
down_revision = "ca3731b65787"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "environments",
        sa.Column("strip_path_prefix", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        schema="sessions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("environments", "strip_path_prefix", schema="sessions")
    # ### end Alembic commands ###
