"""add documentation to projects

Revision ID: f254f678b82b
Revises: 726d5d0e1f28
Create Date: 2024-10-09 12:07:08.959418

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f254f678b82b"
down_revision = "726d5d0e1f28"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("documentation", sa.String(), nullable=True), schema="projects")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "documentation", schema="projects")
    # ### end Alembic commands ###
