"""migrate namespaces to authzed

Revision ID: f34b87ddd954
Revises: d8676f0cde53
Create Date: 2024-05-22 07:56:17.839732

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from sqlalchemy.orm import Session

from renku_data_services.message_queue.avro_models.io.renku.events import v2
from renku_data_services.message_queue.config import RedisConfig
from renku_data_services.message_queue.converters import EventConverter
from renku_data_services.message_queue.db import EventRepository
from renku_data_services.message_queue.models import Event
from renku_data_services.message_queue.redis_queue import RedisQueue
from renku_data_services.migrations.utils import UtilityEventLoop
from renku_data_services.namespace.orm import GroupORM

# revision identifiers, used by Alembic.
revision = "f34b87ddd954"
down_revision = "d8676f0cde53"
branch_labels = None
depends_on = None


async def add_events(session: Session, event_repo: EventRepository, events: list[Event]) -> None:
    for event in events:
        await event_repo.store_event(session, event)


def upgrade() -> None:
    bind = op.get_bind()
    engine = create_async_engine(bind.engine.url)
    session_maker = async_sessionmaker(engine, expire_on_commit=False)
    redis = RedisConfig.from_env()
    message_queue = RedisQueue(redis)
    event_repo = EventRepository(session_maker, message_queue)
    with Session(bind=op.get_bind()) as session, session.begin():
        # Delete all groups
        groups = session.scalars(sa.select(GroupORM)).all()
        for group in groups:
            session.delete(group)
            group_model = group.dump()
            events = EventConverter.to_events(group_model, v2.GroupRemoved)
            UtilityEventLoop.run(add_events(session, event_repo, events))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_common_group_members_group_id", table_name="group_members", schema="common")
    op.drop_table("group_members", schema="common")
    op.drop_index("ix_users_secrets_user_id", table_name="secrets", schema="secrets")
    op.create_index(op.f("ix_secrets_secrets_user_id"), "secrets", ["user_id"], unique=False, schema="secrets")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_secrets_secrets_user_id"), table_name="secrets", schema="secrets")
    op.create_index("ix_users_secrets_user_id", "secrets", ["user_id"], unique=False, schema="secrets")
    op.create_table(
        "group_members",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('common.group_members_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("role", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.VARCHAR(length=26), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["common.groups.id"], name="group_members_group_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.users.keycloak_id"], name="group_members_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="group_members_pkey"),
        schema="common",
    )
    op.create_index("ix_common_group_members_group_id", "group_members", ["group_id"], unique=False, schema="common")
    # ### end Alembic commands ###
