"""add_project_storage

Revision ID: fa511acd4581
Revises: 0a6cee40fe0d
Create Date: 2026-07-09 14:10:42.701383

"""

import sqlalchemy as sa
from alembic import op

from renku_data_services.utils.sqlalchemy import ByteSizeType, ULIDType

# revision identifiers, used by Alembic.
revision = "fa511acd4581"
down_revision = "0a6cee40fe0d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_storage",
        sa.Column("id", ULIDType(), server_default=sa.text("generate_ulid()"), nullable=False),
        sa.Column("project_id", ULIDType(), nullable=False),
        sa.Column("storage_class", sa.String(length=20), nullable=False),
        sa.Column("size_limit", ByteSizeType(), nullable=False),
        sa.Column("target_path", sa.String(), nullable=False),
        sa.Column("created_by_id", sa.String(length=36), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.users.keycloak_id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="storage",
    )
    op.create_index(
        op.f("ix_storage_project_storage_created_by_id"),
        "project_storage",
        ["created_by_id"],
        unique=False,
        schema="storage",
    )
    op.create_index(
        op.f("ix_storage_project_storage_project_id"), "project_storage", ["project_id"], unique=True, schema="storage"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_project_storage_project_id"), table_name="project_storage", schema="storage")
    op.drop_index(op.f("ix_storage_project_storage_created_by_id"), table_name="project_storage", schema="storage")
    op.drop_table("project_storage", schema="storage")
    # ### end Alembic commands ###
