"""data data connector expiry date

Revision ID: fc1a97661d0c
Revises: 2338deb8c428
Create Date: 2026-08-05 09:07:29.527268

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fc1a97661d0c"
down_revision = "2338deb8c428"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_connectors", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True), schema="storage"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_connectors", "expires_at", schema="storage")
    # ### end Alembic commands ###
