"""remove redis message queue

Revision ID: fe3b7470d226
Revises: cfda91a3a6a6
Create Date: 2025-06-30 16:28:18.919140

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fe3b7470d226"
down_revision = "cfda91a3a6a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events", schema="events")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column(
            "id",
            sa.INTEGER(),
            sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("queue", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("timestamp_utc", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="events_pkey"),
        schema="events",
    )
    # ### end Alembic commands ###
