# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-08-19T14:45:28+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, Field, RootModel
from renku_data_services.renku_apps.apispec_base import BaseAPISpec


class AppStatus(StrEnum):
    pending = "pending"
    ready = "ready"
    failed = "failed"


class AppResponse(BaseAPISpec):
    name: str = Field(
        ...,
        description="The name of an app, which is also a DNS label in the app's public hostname.\nThe Kubernetes limit is 63 characters, but names are capped at 50 to leave\nleeway. This must match APP_NAME_MAX_LENGTH in renku_apps/core.py, which is\nthe length generate_app_name() truncates to.\n",
        examples=["my-data-dashboard-0h8kq2zt"],
        max_length=50,
        min_length=5,
        pattern="^[a-z]([-a-z0-9]*[a-z0-9])?$",
    )
    launcher_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    status: AppStatus
    url: str | None = None
    project_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    started: AwareDatetime | None = None
    image: str | None = None


class AppListResponse(RootModel[list[AppResponse]]):
    root: list[AppResponse]


class AppLogsResponse(RootModel[dict[str, str]]):
    root: dict[str, str]


class AppPostRequest(BaseAPISpec):
    launcher_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class AppsGetParametersQuery(BaseAPISpec):
    project_id: str | None = Field(
        None,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )


class AppsAppNameLogsGetParametersQuery(BaseAPISpec):
    max_lines: int = 250
