# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-05-18T09:17:07+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import Field, RootModel
from renku_data_services.renku_apps.apispec_base import BaseAPISpec


class AppStatus(Enum):
    pending = "pending"
    ready = "ready"
    failed = "failed"


class AppResponse(BaseAPISpec):
    name: str = Field(
        ...,
        examples=["d185e68d-d43-renku-2-b9ac279a4e8a85ac28d08"],
        max_length=50,
        min_length=5,
        pattern="^[a-z]([-a-z0-9]*[a-z0-9])?$",
    )
    launcher_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    status: AppStatus
    url: str
    project_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    started: Optional[datetime] = None
    image: Optional[str] = None


class AppPostRequest(BaseAPISpec):
    launcher_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: Optional[str] = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error
