"""Custom resource definition with proper names from the autogenerated code."""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field
from renku_data_services.renku_apps.cr_knative_service import Model as _KnativeService


class Metadata(BaseModel):
    """Basic k8s metadata spec."""

    model_config = ConfigDict(
        # Do not exclude unknown properties.
        extra="allow",
    )

    name: str
    namespace: str | None = None
    labels: dict[str, str] = Field(default_factory=dict)
    annotations: dict[str, str] = Field(default_factory=dict)
    uid: str | None = None
    creationTimestamp: datetime | None = None
    deletionTimestamp: datetime | None = None


class KnativeService(_KnativeService):
    """Knative Service."""

    kind: str = "Service"
    apiVersion: str = "serving.knative.dev/v1"
    metadata: Metadata  # type: ignore[assignment]
