"""Custom resource definition with proper names from the autogenerated code."""

from collections.abc import Mapping
from datetime import datetime
from typing import cast

from pydantic import BaseModel, ConfigDict, Field
from ulid import ULID

from renku_data_services.errors import errors
from renku_data_services.renku_apps.cr_knative_service import Limits as _Limits
from renku_data_services.renku_apps.cr_knative_service import Limits1 as LimitsStr
from renku_data_services.renku_apps.cr_knative_service import Model as _KnativeService
from renku_data_services.renku_apps.cr_knative_service import Requests as _Requests
from renku_data_services.renku_apps.cr_knative_service import Requests1 as RequestsStr
from renku_data_services.renku_apps.cr_knative_service import Resources as _Resources


class Metadata(BaseModel):
    """Basic k8s metadata spec."""

    model_config = ConfigDict(
        # Do not exclude unknown properties.
        extra="allow",
    )

    name: str
    namespace: str | None = None
    labels: dict[str, str] = Field(default_factory=dict)
    annotations: dict[str, str] = Field(default_factory=dict)
    uid: str | None = None
    creationTimestamp: datetime | None = None
    deletionTimestamp: datetime | None = None


class Requests(_Requests):
    """Resource requests of type integer."""

    root: int


class Limits(_Limits):
    """Resource limits of type integer."""

    root: int


class Resources(_Resources):
    """Resource requests and limits spec.

    Overriding these is necessary because of
    https://docs.pydantic.dev/2.11/errors/validation_errors/#string_type.
    An integer model cannot have a regex pattern for validation in pydantic.
    But the code generation applies the pattern constraint to both the int and string variations
    of the fields. But the int variation runs and blows up at runtime only when an int is passed
    for validation.
    """

    limits: Mapping[str, LimitsStr | Limits] | None = None
    requests: Mapping[str, RequestsStr | Requests] | None = None


class KnativeService(_KnativeService):
    """Knative Service."""

    kind: str = "Service"
    apiVersion: str = "serving.knative.dev/v1"
    metadata: Metadata  # type: ignore[assignment]

    @property
    def launcher_id(self) -> ULID:
        """Get the session launcher ID from the labels."""
        if "renku.io/launcher-id" not in self.metadata.labels:
            raise errors.ProgrammingError(
                message=f"The app with name {self.metadata.name} is missing its launcher-id label"
            )
        return cast(ULID, ULID.from_str(self.metadata.labels["renku.io/launcher-id"]))

    @property
    def project_id(self) -> ULID:
        """Get the project ID from the labels."""
        if "renku.io/project-id" not in self.metadata.labels:
            raise errors.ProgrammingError(
                message=f"The app with name {self.metadata.name} is missing its project-id label"
            )
        return cast(ULID, ULID.from_str(self.metadata.labels["renku.io/project-id"]))
