"""create_tables

Revision ID: 62935e3d8520
Revises:
Create Date: 2024-01-21 11:55:22.234901

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62935e3d8520"
down_revision = None
branch_labels = ("secrets",)
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secrets",
        sa.Column("id", sa.String(26), nullable=False),
        sa.Column("name", sa.String(99), nullable=False),
        sa.Column("value", sa.String(length=5000), nullable=False),
        sa.Column("modification_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="secrets",
    )
    op.create_index(
        op.f("ix_secrets_secrets_user_id"),
        "secrets",
        ["user_id"],
        unique=False,
        schema="secrets",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_secrets_secrets_user_id"), table_name="secrets", schema="secrets")
    op.drop_table("secrets", schema="secrets")
    # ### end Alembic commands ###
