# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2024-04-08T13:48:13+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.secret.apispec_base import BaseAPISpec


class Ulid(RootModel[str]):
    root: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[A-Z0-9]{26}$",
    )


class K8sSecret(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    K8sSecretName: str = Field(
        ...,
        description="The name of the k8s secret to create",
        example="john-doe-session-57-secret",
    )
    SecretIds: List[Ulid] = Field(
        ..., description="The ids of the secrets to include", min_length=1
    )
    Owner: Optional[str] = Field(
        None,
        description="The resource in K8s that owns this secret",
        example="john-doe-session-57",
    )
