---
apiVersion: shipwright.io/v1beta1
kind: ClusterBuildStrategy
metadata:
  name: renku-buildpacks
spec:
  parameters:
    - name: platform-api-version
      description: The referenced version is the minimum version that all relevant buildpack implementations support.
      default: "0.12"
    - name: process-type
      description: |
        The process to execute at launch time
        https://buildpacks.io/docs/for-buildpack-authors/how-to/write-buildpacks/specify-launch-processes/
      default: "web"
  steps:
    - name: build-and-push
      image: docker.io/paketobuildpacks/builder-jammy-full:latest
      imagePullPolicy: IfNotPresent
      env: 
        - name: CNB_PLATFORM_API
          value: $(params.platform-api-version)
      command:
        - /cnb/lifecycle/creator
      args:
        - "-app=$(params.shp-source-context)"
        - "-report=/tmp/report.toml"
        - "-process-type=$(params.process-type)"
        - "$(params.shp-output-image)"
      volumeMounts:
        - mountPath: /platform/env
          name: platform-env
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
  volumes:
    - name: platform-env
      emptyDir: {}
  securityContext:
    runAsUser: 1001
    runAsGroup: 1000
