# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-02-17T20:15:51+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.repositories.apispec_base import BaseAPISpec


class Status(Enum):
    valid = "valid"
    invalid = "invalid"
    unknown = "unknown"


class ErrorCode(Enum):
    no_url_scheme = "no_url_scheme"
    no_url_host = "no_url_host"
    no_git_repo = "no_git_repo"
    no_url_path = "no_url_path"
    invalid_url_scheme = "invalid_url_scheme"
    invalid_git_url = "invalid_git_url"
    metadata_unauthorized = "metadata_unauthorized"
    metadata_oauth = "metadata_oauth"
    metadata_unknown = "metadata_unknown"
    metadata_validation = "metadata_validation"


class RepositoryVisibility(Enum):
    public = "public"
    private = "private"


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: Optional[str] = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class RepositoryGetParametersQuery(BaseAPISpec):
    url: str


class Metadata(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    git_url: str
    web_url: Optional[str] = None
    pull_permission: bool
    push_permission: Optional[bool] = None
    visibility: RepositoryVisibility


class ProviderConnection(BaseAPISpec):
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    provider_id: str = Field(
        ...,
        description='ID of a OAuth2 provider, e.g. "gitlab.com".',
        examples=["some-id"],
    )
    status: str


class ProviderData(BaseAPISpec):
    id: str = Field(
        ...,
        description='ID of a OAuth2 provider, e.g. "gitlab.com".',
        examples=["some-id"],
    )
    name: str
    url: str


class RepositoryProviderData(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status
    connection: Optional[ProviderConnection] = None
    provider: Optional[ProviderData] = None
    metadata: Optional[Metadata] = None
    error_code: Optional[ErrorCode] = None
