apiVersion: kpack.io/v1alpha2
kind: Builder
metadata:
  name: python-builder
  namespace: default
spec:
  tag: kpack-registry.local:5000/apps/python-builder:latest
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
  - group:
    - id: paketo-buildpacks/python
    - id: paketo-buildpacks/procfile
    - id: paketo-buildpacks/source-removal
    - id: paketo-buildpacks/environment-variables
