# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-07-30T15:37:23+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.storage.apispec_base import BaseAPISpec


class RCloneConfigValidate(
    RootModel[dict[str, int | str | bool | dict[str, Any] | None]]
):
    root: dict[str, int | str | bool | dict[str, Any] | None]


class Example(BaseAPISpec):
    value: str = Field(..., description="a potential value for the option (think enum)")
    help: str = Field(..., description="help text for the value")
    provider: str | None = Field(
        None,
        description="The provider this value is applicable for. Empty if valid for all providers.",
    )


class Type(StrEnum):
    int = "int"
    bool = "bool"
    string = "string"
    stringArray = "stringArray"
    Time = "Time"
    Duration = "Duration"
    MultiEncoder = "MultiEncoder"
    SizeSuffix = "SizeSuffix"
    SpaceSepList = "SpaceSepList"
    CommaSepList = "CommaSepList"
    Tristate = "Tristate"
    Encoding = "Encoding"
    Bits = "Bits"


class RCloneOption(BaseAPISpec):
    name: str = Field(..., description="name of the option")
    help: str = Field(..., description="help text for the option")
    provider: str | None = Field(
        None,
        description="The cloud provider the option is for (See 'provider' RCloneOption in the schema for potential values)",
        examples=["AWS"],
    )
    default: float | str | bool | dict[str, Any] | list[Any] = Field(
        ..., description="default value for the option"
    )
    default_str: str = Field(
        ..., description="string representation of the default value"
    )
    examples: list[Example] | None = Field(
        None,
        description="These list potential values for this option, like an enum. With `exclusive: true`, only a value from the list is allowed.",
    )
    required: bool = Field(..., description="whether the option is required or not")
    ispassword: bool = Field(
        ..., description="whether the field is a password (use **** for display)"
    )
    sensitive: bool = Field(
        ...,
        description="whether the value is sensitive (not stored in the service). Do not send this in requests to the service.",
    )
    advanced: bool = Field(
        ...,
        description="whether this is an advanced config option (probably don't show these to users)",
    )
    exclusive: bool = Field(
        ..., description="if true, only values from 'examples' can be used"
    )
    type: Type = Field(
        ...,
        description="data type of option value. RClone has more options but they map to the ones listed here.",
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class ProjectStoragePatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    size: int | None = Field(None, description="The maximum size in GB")
    mount_path: str | None = Field(None, description="The mount path for the storage")


class ProjectStorageAllowPatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_size: int | None = Field(None, description="The maximum size in GB")


class ProjectStorageConfig(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    max_size: int = Field(..., description="The maximum size in GB")


class StorageSchemaTestConnectionPostRequest(BaseAPISpec):
    configuration: dict[str, int | str | bool | dict[str, Any] | None]
    source_path: str = Field(
        ...,
        description="the source path to mount, usually starts with bucket/container name",
        examples=["bucket/my/storage/folder/"],
    )


class StorageSchemaObscurePostRequest(BaseAPISpec):
    configuration: dict[str, int | str | bool | dict[str, Any] | None]


class PaginationRequest(RootModel[Any]):
    root: Any


class ProjectStorageList(RootModel[Any]):
    root: Any


class RCloneEntry(BaseAPISpec):
    name: str = Field(..., description="Human readable name of the provider")
    description: str = Field(..., description="description of the provider")
    prefix: str = Field(..., description="Machine readable name of the provider")
    options: list[RCloneOption] = Field(
        ..., description="Fields/properties used for this storage."
    )


class ProjectStoragePost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    namespace: Any
    size: int
    mount_path: str


class ProjectStorage(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Any
    project_id: Any
    size: int
    mount_path: str
    creation_date: Any
    created_by: Any
    updated_at: Any
    etag: Any


class ProjectStorageAllowPost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Any
    max_size: int = Field(..., description="Maximum size in GB")


class ProjectStorageAllow(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: Any
    name: str
    namespace: str
    max_size: int = Field(..., description="Maximum size in GB")
    etag: Any


class ProjectStorageAllowList(RootModel[list[ProjectStorageAllow]]):
    root: list[ProjectStorageAllow] = Field(
        ..., description="A list of project storage allow entries.\n"
    )


class ProjectStorageAllowListQuery(BaseAPISpec):
    project_name: str = Field("", description="Filter by project name (partial match).")


class DataConnectorsStorageAllowGetParametersQuery(BaseAPISpec):
    params: ProjectStorageAllowListQuery | None = None


class RCloneSchema(RootModel[list[RCloneEntry]]):
    root: list[RCloneEntry] = Field(
        ..., description="List of RClone schemas for different storage types"
    )
