# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-08-19T12:27:41+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.storage.apispec_base import BaseAPISpec


class RCloneConfigValidate(
    RootModel[Optional[Dict[str, Union[int, Optional[str], bool, Dict[str, Any]]]]]
):
    root: Optional[Dict[str, Union[int, Optional[str], bool, Dict[str, Any]]]] = None


class Example(BaseAPISpec):
    value: str = Field(..., description="a potential value for the option (think enum)")
    help: str = Field(..., description="help text for the value")
    provider: Optional[str] = Field(
        None,
        description="The provider this value is applicable for. Empty if valid for all providers.",
    )


class Type(Enum):
    int = "int"
    bool = "bool"
    string = "string"
    stringArray = "stringArray"
    Time = "Time"
    Duration = "Duration"
    MultiEncoder = "MultiEncoder"
    SizeSuffix = "SizeSuffix"
    SpaceSepList = "SpaceSepList"
    CommaSepList = "CommaSepList"
    Tristate = "Tristate"
    Encoding = "Encoding"
    Bits = "Bits"


class RCloneOption(BaseAPISpec):
    name: str = Field(..., description="name of the option")
    help: str = Field(..., description="help text for the option")
    provider: Optional[str] = Field(
        None,
        description="The cloud provider the option is for (See 'provider' RCloneOption in the schema for potential values)",
        examples=["AWS"],
    )
    default: Union[float, str, bool, Dict[str, Any], List] = Field(
        ..., description="default value for the option"
    )
    default_str: str = Field(
        ..., description="string representation of the default value"
    )
    examples: Optional[List[Example]] = Field(
        None,
        description="These list potential values for this option, like an enum. With `exclusive: true`, only a value from the list is allowed.",
    )
    required: bool = Field(..., description="whether the option is required or not")
    ispassword: bool = Field(
        ..., description="whether the field is a password (use **** for display)"
    )
    sensitive: bool = Field(
        ...,
        description="whether the value is sensitive (not stored in the service). Do not send this in requests to the service.",
    )
    advanced: bool = Field(
        ...,
        description="whether this is an advanced config option (probably don't show these to users)",
    )
    exclusive: bool = Field(
        ..., description="if true, only values from 'examples' can be used"
    )
    type: Type = Field(
        ...,
        description="data type of option value. RClone has more options but they map to the ones listed here.",
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: Optional[str] = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class ProjectStoragePatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    size: Optional[int] = Field(None, description="The maximum size in GB")
    mount_path: Optional[str] = Field(
        None, description="The mount path for the storage"
    )


class ProjectStorageAllowPatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_size: Optional[int] = Field(None, description="Maximum size in GB", gt=0)


class ProjectStorageConfig(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    enabled: bool
    max_size: int = Field(..., description="Maximum size in GB", gt=0)


class PaginationRequest(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    page: int = Field(1, description="Result's page number starting from 1", ge=1)
    per_page: int = Field(
        20, description="The number of results per page", ge=1, le=100
    )


class StorageSchemaTestConnectionPostRequest(BaseAPISpec):
    configuration: Dict[str, Union[int, Optional[str], bool, Dict[str, Any]]]
    source_path: str = Field(
        ...,
        description="the source path to mount, usually starts with bucket/container name",
        examples=["bucket/my/storage/folder/"],
    )


class StorageSchemaObscurePostRequest(BaseAPISpec):
    configuration: Dict[str, Union[int, Optional[str], bool, Dict[str, Any]]]


class RCloneEntry(BaseAPISpec):
    name: str = Field(..., description="Human readable name of the provider")
    description: str = Field(..., description="description of the provider")
    prefix: str = Field(..., description="Machine readable name of the provider")
    options: List[RCloneOption] = Field(
        ..., description="Fields/properties used for this storage."
    )


class ProjectStoragePost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    namespace: str = Field(
        ...,
        description="The slug used to identify a project",
        examples=["user/my-project"],
        min_length=3,
        pattern="^[a-zA-Z0-9]+([_.\\-/][a-zA-Z0-9]+)*[_.\\-/]?[a-zA-Z0-9]$",
    )
    size: int
    mount_path: str


class ProjectStorage(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    project_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    size: int
    mount_path: str
    creation_date: datetime = Field(
        ...,
        description="The date and time the resource was created (in UTC and ISO-8601 format)",
        examples=["2023-11-01T17:32:28Z"],
    )
    created_by: str = Field(
        ...,
        description="Keycloak user ID",
        examples=["f74a228b-1790-4276-af5f-25c2424e9b0c"],
        pattern="^[A-Za-z0-9]{1}[A-Za-z0-9-]+$",
    )
    updated_at: datetime = Field(
        ...,
        description="The date and time the resource was created (in UTC and ISO-8601 format)",
        examples=["2023-11-01T17:32:28Z"],
    )
    etag: str = Field(
        ..., description="Entity Tag", examples=["9EE498F9D565D0C41E511377425F32F3"]
    )


class ProjectStorageAllowPost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    max_size: int = Field(..., description="Maximum size in GB", gt=0)


class ProjectStorageAllow(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    name: str
    namespace: str
    max_size: int = Field(..., description="Maximum size in GB", gt=0)
    etag: str = Field(
        ..., description="Entity Tag", examples=["9EE498F9D565D0C41E511377425F32F3"]
    )


class ProjectStorageList(RootModel[List[ProjectStorage]]):
    root: List[ProjectStorage] = Field(..., description="A list of project storages.")


class ProjectStorageAllowList(RootModel[List[ProjectStorageAllow]]):
    root: List[ProjectStorageAllow] = Field(
        ..., description="A list of project storage allow entries.\n"
    )


class ProjectStorageAllowListQuery(PaginationRequest):
    model_config = ConfigDict(
        extra="forbid",
    )
    project_name: str = Field("", description="Filter by project name (partial match).")


class StorageAllowGetParametersQuery(BaseAPISpec):
    params: Optional[ProjectStorageAllowListQuery] = None


class RCloneSchema(RootModel[List[RCloneEntry]]):
    root: List[RCloneEntry] = Field(
        ..., description="List of RClone schemas for different storage types"
    )
