---
openapi: 3.0.2
info:
  title: Renku user preferences services
  description: |
    Services that provide information about user preferences.
  version: v1
servers:
  - url: /api/data
  - url: /ui-server/api/data
paths:
  "/user/preferences":
    get:
      summary: Get user preferences for the currently logged in user
      parameters:
        - $ref: "#/components/parameters/If-None-Match"
      responses:
        "200":
          description: The user preferences
          headers:
            ETag:
              $ref: "#/components/headers/ETag"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPreferences"
        "404":
          description: The user has no preferences saved
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - user_preferences
    patch:
      summary: Update specific fields of a user preferences object
      parameters:
        - $ref: "#/components/parameters/If-Match"
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UserPreferencesPatch"
      responses:
        "200":
          description: The updated user preferences
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPreferences"
        "409":
          description: The update conflicts with the current state on the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - user_preferences


  "/user/preferences/pinned_projects":
    post:
      summary: Add a pinned project
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/AddPinnedProject"
      responses:
        "200":
          description: The updated user preferences
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPreferences"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - user_preferences
    delete:
      summary: Remove one or all pinned projects
      parameters:
        - in: query
          name: project_slug
          schema:
            type: string
      responses:
        "200":
          description: The updated user preferences
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPreferences"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - user_preferences

components:
  schemas:
    UserPreferences:
      type: object
      description: The object containing user preferences
      additionalProperties: false
      properties:
        user_id:
          $ref: "#/components/schemas/UserId"
        pinned_projects:
          $ref: "#/components/schemas/PinnedProjects"
      required: ["user_id", "pinned_projects"]
    UserPreferencesPatch:
      type: object
      description: Update user preferences
      additionalProperties: false
      properties:
        pinned_projects:
          $ref: "#/components/schemas/PinnedProjects"
    UserId:
      type: string
      description: The unique identifier for a user
      minLength: 3
      example: "user-id-example"
    PinnedProjects:
      type: object
      description: The list of projects a user has pinned on their dashboard
      properties:
        project_slugs:
          type: array
          items:
            $ref: "#/components/schemas/ProjectSlug"
    ProjectSlug:
      type: string
      description: The slug used to identify a project
      minLength: 3
      example: "user/my-project"
      # limitations based on allowed characters in project slugs from Gitlab from here:
      # https://docs.gitlab.com/ee/user/reserved_names.html
      pattern: "[a-zA-Z0-9_.-/]"
    AddPinnedProject:
      type: object
      additionalProperties: false
      properties:
        project_slug:
          $ref: "#/components/schemas/ProjectSlug"
      required: ["project_slug"]
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              minimum: 0
              exclusiveMinimum: true
              example: 1404
            detail:
              type: string
              example: "A more detailed optional message showing what the problem was"
            message:
              type: string
              example: "Something went wrong - please try again later"
          required: ["code", "message"]
      required: ["error"]
    ETag:
      type: string
      description: Entity Tag
      example: "9EE498F9D565D0C41E511377425F32F3"

  responses:
    Error:
      description: The schema for all 4xx and 5xx responses
      content:
        "application/json":
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  headers:
    ETag:
      description: Entity Tag header
      required: true
      schema:
        $ref: "#/components/schemas/ETag"

  parameters:
    If-Match:
      in: header
      name: If-Match
      description: If-Match header, for avoiding mid-air collisions
      required: false
      schema:
        $ref: "#/components/schemas/ETag"
    If-None-Match:
      in: header
      name: If-None-Match
      description: If-None-Match header, for caching entities
      required: false
      schema:
        $ref: "#/components/schemas/ETag"

  securitySchemes:
    oidc:
      type: openIdConnect
      openIdConnectUrl: /auth/realms/Renku/.well-known/openid-configuration
security:
  - oidc:
      - openid
