---
openapi: 3.0.2
info:
  title: Renku user preferences services
  description: |
    Services that provide information about user preferences.
  version: v1
servers:
  - url: /api/data
  - url: /ui-server/api/data
paths:
  /user_preferences:
    get:
      summary: Get user preferences for the currently logged in user
      responses:
        "200":
          description: The user preferences
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPreferences"
        "404":
          description: The user has no preferences saved
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - user_preferences
    post:
      summary: Create user preferences for the currently logged in user
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UserPreferencesWithoutUserId"
      responses:
        "201":
          description: The newly created user preferences
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPreferences"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - user_preferences
    patch:
      summary: Partially update user preferences for the currently logged in user
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/UserPreferencesWithoutUserId"
      responses:
        "200":
          description: The updated user preferences
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/UserPreferences"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - user_preferences

components:
  schemas:
    UserPreferencesWithoutUserId:
      type: object
      description: The object containing user preferences
      additionalProperties: false
      properties:
        pinned_projects:
          $ref: "#/components/schemas/PinnedProjects"
    UserPreferences:
      type: object
      description: The object containing user preferences
      additionalProperties: false
      properties:
        user_id:
          $ref: "#/components/schemas/UserId"
        pinned_projects:
          $ref: "#/components/schemas/PinnedProjects"
      required: ["user_id", "pinned_projects"]
    UserId:
      type: string
      description: The unique identifier for a user
      minLength: 3
      example: "user-id-example"
    PinnedProjects:
      type: object
      description: The list of projects a user has pinned on their dashboard
      properties:
        project_slugs:
          type: array
          items:
            $ref: "#/components/schemas/ProjectSlug"
    ProjectSlug:
      type: string
      description: The slug used to identify a project
      minLength: 3
      example: "user/my-project"
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              minimum: 0
              exclusiveMinimum: true
              example: 1404
            detail:
              type: string
              example: "A more detailed optional message showing what the problem was"
            message:
              type: string
              example: "Something went wrong - please try again later"
          required: ["code", "message"]
      required: ["error"]

  responses:
    Error:
      description: The schema for all 4xx and 5xx responses
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  securitySchemes:
    oidc:
      type: openIdConnect
      openIdConnectUrl: /auth/realms/Renku/.well-known/openid-configuration
security:
  - oidc:
      - openid
