# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-09-30T08:58:45+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, ConfigDict, Field, RootModel
from renku_data_services.session_runners.apispec_base import BaseAPISpec


class UserSessionRunnerPost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_pool_id: int


class Status(StrEnum):
    ready = "ready"
    not_ready = "not_ready"


class UserSessionRunnerPatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    status: Status


class UserSessionRunnerRegisterPost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    registration_token: str


class Auth(BaseAPISpec):
    model_config = ConfigDict(
        extra="allow",
    )
    access_token: str = Field(..., examples=["some_access_token"])
    token_type: str = Field(..., examples=["Bearer"])
    expires_in: int = Field(..., examples=[600])
    refresh_token: str = Field(..., examples=["some_refresh_token"])
    refresh_expires_in: int | None = Field(None, examples=[3600])
    scope: str | None = Field(None, examples=["api"])


class UserSessionRunnerStatus(StrEnum):
    never_contacted = "never_contacted"
    initializing = "initializing"
    ready = "ready"
    not_ready = "not_ready"


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class SessionRunnersUserGetParametersQuery(BaseAPISpec):
    all_users: bool | None = Field(
        None,
        description="If true, an admin will see the list of runners from all users.\n",
    )


class UserSessionRunner(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    user_id: str | None = Field(
        None,
        description="Keycloak user ID",
        examples=["f74a228b-1790-4276-af5f-25c2424e9b0c"],
        pattern="^[A-Za-z0-9]{1}[A-Za-z0-9-]+$",
    )
    resource_pool_id: int
    status: UserSessionRunnerStatus
    registration_token: str | None = None
    creation_date: AwareDatetime = Field(
        ...,
        description="The date and time the resource was created (in UTC and ISO-8601 format)",
        examples=["2023-11-01T17:32:28Z"],
    )
    last_contact: AwareDatetime | None = Field(
        None,
        description="The date and time the resource was updated (in UTC and ISO-8601 format)",
        examples=["2023-11-01T17:32:28Z"],
    )


class UserSessionRunnerRegisterResponse(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    runner: UserSessionRunner
    auth: Auth


class UserSessionRunners(RootModel[list[UserSessionRunner]]):
    root: list[UserSessionRunner] = Field(
        ..., description="A list of user-scoped session runners"
    )
