# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-09-09T08:07:20+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import ConfigDict, Field
from renku_data_services.session_runners.apispec_base import BaseAPISpec


class SessionRunnerPost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_pool_id: int


class SessionRunnerStatus(StrEnum):
    never_contacted = "never_contacted"
    initializing = "initializing"
    ready = "ready"
    not_ready = "not_ready"


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class SessionRunner(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    resource_pool_id: int
    status: SessionRunnerStatus
    registration_token: str | None = None
