openapi: 3.0.2
info:
  title: Renku Data Services API
  description: |
    This service is the main backend for Renku. It provides information about users, projects,
    cloud storage, access to compute resources and many other things.
  version: v1
servers:
  - url: /api/data
  - url: /ui-server/api/data
paths:
  /environments:
    get:
      summary: Get all global environments
      responses:
        "200":
          description: List of global environments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EnvironmentList"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - environments
    post:
      summary: Create a new global session environment
      description: Requires admin permissions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnvironmentPost"
      responses:
        "201":
          description: The session environment was created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Environment"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - environments
  /environments/{environment_id}:
    get:
      summary: Get a global session environment
      parameters:
        - in: path
          name: environment_id
          required: true
          schema:
            $ref: "#/components/schemas/Ulid"
      responses:
        "200":
          description: The session environment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Environment"
        "404":
          description: The session environment does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - environments
    patch:
      summary: Update specific fields of an existing global session environment
      description: Requires admin permissions
      parameters:
        - in: path
          name: environment_id
          required: true
          schema:
            $ref: "#/components/schemas/Ulid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnvironmentPatch"
      responses:
        "200":
          description: The patched session environment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Environment"
        "404":
          description: The session environment does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - environments
    delete:
      summary: Remove a global session environment
      parameters:
        - in: path
          name: environment_id
          required: true
          schema:
            $ref: "#/components/schemas/Ulid"
      responses:
        "204":
          description: The session environment was removed or did not exist in the first place
        default:
          $ref: "#/components/responses/Error"
      tags:
        - environments
  /session_launchers:
    get:
      summary: Get all user's session launchers
      responses:
        "200":
          description: List of sessions launchers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionLaunchersList"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - session_launchers
    post:
      summary: Create a new session launcher
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionLauncherPost"
      responses:
        "201":
          description: The session launcher was created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionLauncher"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - session_launchers
  /session_launchers/{launcher_id}:
    get:
      summary: Get a session launcher
      parameters:
        - in: path
          name: launcher_id
          required: true
          schema:
            $ref: "#/components/schemas/Ulid"
      responses:
        "200":
          description: The session launcher
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionLauncher"
        "404":
          description: The session launcher does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - session_launchers
    patch:
      summary: Update specific fields of an existing session launcher
      parameters:
        - in: path
          name: launcher_id
          required: true
          schema:
            $ref: "#/components/schemas/Ulid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionLauncherPatch"
      responses:
        "200":
          description: The patched session launcher
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionLauncher"
        "404":
          description: The session launcher does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - session_launchers
    delete:
      summary: Remove a session launcher
      parameters:
        - in: path
          name: launcher_id
          required: true
          schema:
            $ref: "#/components/schemas/Ulid"
      responses:
        "204":
          description: The session was removed or did not exist in the first place
        default:
          $ref: "#/components/responses/Error"
      tags:
        - session_launchers
  /projects/{project_id}/session_launchers:
    get:
      summary: Get a project's session launchers
      parameters:
        - in: path
          name: project_id
          required: true
          schema:
            $ref: "#/components/schemas/Ulid"
      responses:
        "200":
          description: List of sessions launchers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionLaunchersList"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - session_launchers
components:
  schemas:
    EnvironmentList:
      description: A list of session environments
      type: array
      items:
        $ref: "#/components/schemas/Environment"
    Environment:
      description: A Renku 2.0 session environment
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Ulid"
        name:
          $ref: "#/components/schemas/SessionName"
        creation_date:
          $ref: "#/components/schemas/CreationDate"
        description:
          $ref: "#/components/schemas/Description"
        container_image:
          $ref: "#/components/schemas/ContainerImage"
        default_url:
          $ref: "#/components/schemas/DefaultUrl"
        uid: 
          $ref: "#/components/schemas/EnvironmentUid"
        gid: 
          $ref: "#/components/schemas/EnvironmentGid"
        working_directory:
          $ref: "#/components/schemas/EnvironmentWorkingDirectory"
        mount_directory:
          $ref: "#/components/schemas/EnvironmentMountDirectory"
        port:
          $ref: "#/components/schemas/EnvironmentPort"
      required:
        - id
        - name
        - creation_date
        - container_image
        - port
        - working_directory
        - mount_directory
        - uid
        - gid
        - default_url
      example:
        id: 01AN4Z79ZS6XX96588FDX0H099
        name: JupyterLab environment
        creation_date: "2023-11-01T17:32:28Z"
        description: JupyterLab session environment
        container_image: renku-jupyter:latest
        default_url: "/lab"
        port: 8080
        working_directory: /home/jovyan/work
        mount_directory: /home/jovyan/work
        uid: 1000
        gid: 1000
    EnvironmentGetInLauncher:
      allOf:
        - $ref: "#/components/schemas/Environment"
        - type: object
          properties:
            environment_kind:
              $ref: "#/components/schemas/EnvironmentKind"
          required:
            - environment_kind
          example:
            environment_kind: global_environment
    EnvironmentPostInLauncher:
      allOf:
        - $ref: "#/components/schemas/EnvironmentPost"
        - type: object
          properties:
            environment_kind:
              $ref: "#/components/schemas/EnvironmentKind"
          required:
            - environment_kind
          example:
            environment_kind: global_environment
    EnvironmentPost:
      description: Data required to create a session environment
      type: object
      properties:
        name:
          $ref: "#/components/schemas/SessionName"
        description:
          $ref: "#/components/schemas/Description"
        container_image:
          $ref: "#/components/schemas/ContainerImage"
        default_url:
          allOf:
            - $ref: "#/components/schemas/DefaultUrl"
            - default: /lab
        uid: 
          allOf:
            - $ref: "#/components/schemas/EnvironmentUid"
            - default: 1000
        gid: 
          allOf:
            - $ref: "#/components/schemas/EnvironmentGid"
            - default: 1000
        working_directory:
          allOf:
            - $ref: "#/components/schemas/EnvironmentWorkingDirectory"
            - default: /home/jovyan/work
        mount_directory:
          allOf:
            - $ref: "#/components/schemas/EnvironmentMountDirectory"
            - default: /home/jovyan/work
        port:
          allOf:
            - $ref: "#/components/schemas/EnvironmentPort"
            - default: 8080
      required:
        - name
        - container_image
    EnvironmentPatchInLauncher:
      allOf:
        - $ref: "#/components/schemas/EnvironmentPatch"
        - type: object
          properties:
            environment_kind:
              $ref: "#/components/schemas/EnvironmentKind"
          example:
            environment_kind: global_environment
    EnvironmentPatch:
      type: object
      description: Update a session environment
      additionalProperties: false
      properties:
        name:
          $ref: "#/components/schemas/SessionName"
        description:
          $ref: "#/components/schemas/Description"
        container_image:
          $ref: "#/components/schemas/ContainerImage"
        default_url:
          $ref: "#/components/schemas/DefaultUrl"
        uid: 
          $ref: "#/components/schemas/EnvironmentUid"
        gid: 
          $ref: "#/components/schemas/EnvironmentGid"
        working_directory:
          $ref: "#/components/schemas/EnvironmentWorkingDirectory"
        mount_directory:
          $ref: "#/components/schemas/EnvironmentMountDirectory"
        port:
          $ref: "#/components/schemas/EnvironmentPort"
    SessionLaunchersList:
      description: A list of Renku session launchers
      type: array
      items:
        $ref: "#/components/schemas/SessionLauncher"
      minItems: 0
    SessionLauncher:
      description: A Renku 2.0 session definition and metadata
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Ulid"
        project_id:
          $ref: "#/components/schemas/Ulid"
        name:
          $ref: "#/components/schemas/SessionName"
        creation_date:
          $ref: "#/components/schemas/CreationDate"
        description:
          $ref: "#/components/schemas/Description"
        environment:
          $ref: "#/components/schemas/EnvironmentGetInLauncher"
      required:
        - id
        - project_id
        - name
        - creation_date
        - environment
      example:
        id: 01AN4Z79ZS5XN0F25N3DB94T4R
        project_id: 01AN4Z79ZS5XN0F25N3DB94T4R
        name: Renku R Session
        creation_date: "2023-11-01T17:32:28Z"
        description: R compute session
        environment:
          id: 01AN4Z79ZS6XX96588FDX0H099
          name: Rstudio
          creation_date: "2023-11-01T17:32:28Z"
          description: JupyterLab session environment
          environment_kind: global_environment
          container_image: rocker/rstudio
          default_url: "/rstudio"
          port: 8080
          working_directory: /home/rstudio/work
          mount_directory: /home/rstudio/work
          uid: 1000
          gid: 1000
    SessionLauncherPost:
      description: Data required to create a session launcher
      type: object
      additionalProperties: false
      properties:
        name:
          $ref: "#/components/schemas/SessionName"
        project_id:
          $ref: "#/components/schemas/Ulid"
        description:
          $ref: "#/components/schemas/Description"
        resource_class_id:
          $ref: "#/components/schemas/ResourceClassId"
        environment:
          oneOf:
            - $ref: "#/components/schemas/EnvironmentPostInLauncher"
            - $ref: "#/components/schemas/EnvironmentIdOnlyPost"
      required:
        - name
        - project_id
        - environment
    SessionLauncherPatch:
      type: object
      description: Update a session launcher
      additionalProperties: false
      properties:
        name:
          $ref: "#/components/schemas/SessionName"
        description:
          $ref: "#/components/schemas/Description"
        resource_class_id:
          $ref: "#/components/schemas/ResourceClassId"
        environment:
          oneOf:
            - $ref: "#/components/schemas/EnvironmentPatchInLauncher"
            - $ref: "#/components/schemas/EnvironmentIdOnlyPatch"
    Ulid:
      description: ULID identifier
      type: string
      minLength: 26
      maxLength: 26
      pattern: "^[A-Z0-9]{26}$" # This is case-insensitive
    SessionName:
      description: Renku session name
      type: string
      minLength: 1
      maxLength: 99
      example: My Renku Session :)
    EnvironmentIdOnlyPatch:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/EnvironmentId"
    EnvironmentIdOnlyPost:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/EnvironmentId"
      required:
        - id
    EnvironmentKind:
      description: Kind of environment to use
      type: string
      enum:
        - global_environment
        - container_image
      example: container_image
    EnvironmentId:
      description: Id of the environment to use
      type: string
      minLength: 1
      example: 01AN4Z79ZS6XX96588FDX0H099
    CreationDate:
      description: The date and time the resource was created (in UTC and ISO-8601 format)
      type: string
      format: date-time
      example: "2023-11-01T17:32:28Z"
    Description:
      description: A description for the resource
      type: string
      maxLength: 500
    ContainerImage:
      description: A container image
      type: string
      maxLength: 500
      example: renku/renkulab-py:3.10-0.18.1
    DefaultUrl:
      description: The default path to open in a session
      type: string
      maxLength: 200
      example: "/lab"
    ResourceClassId:
      description: The identifier of a resource class
      type: integer
      default: null
      nullable: true
    EnvironmentPort:
      type: integer
      minimum: 0
      exclusiveMinimum: true
      maximum: 65535
      description: The TCP port (on any container in the session) where user requests will be routed to from the ingress
    EnvironmentUid:
      type: integer
      minimum: 0
      exclusiveMinimum: true
      maximum: 65535
      description: The user ID used to run the session
    EnvironmentGid:
      type: integer
      minimum: 0
      exclusiveMinimum: true
      maximum: 65535
      description: The group ID used to run the session
    EnvironmentWorkingDirectory:
      type: string
      description: The location where the session will start
      minLength: 1
    EnvironmentMountDirectory:
      type: string
      description: The location where the persistent storage for the session will be mounted, usually it should be identical to or a parent of the working directory
      minLength: 1
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              minimum: 0
              exclusiveMinimum: true
              example: 1404
            detail:
              type: string
              example: A more detailed optional message showing what the problem was
            message:
              type: string
              example: Something went wrong - please try again later
          required:
            - code
            - message
      required:
        - error
  responses:
    Error:
      description: The schema for all 4xx and 5xx responses
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
