"""Custom resource definition with proper names from the autogenerated code."""

from renku_data_services.session.cr_shipwright_buildrun import Model as _BuildRun

class BuildRun(_BuildRun):
    """ShipWright BuildRun."""
    pass
