"""Custom resource definition with proper names from the autogenerated code."""

from datetime import datetime

from pydantic import BaseModel, Field, RootModel

from renku_data_services.session.cr_shipwright_buildrun import Build, Git, ParamValue, Strategy, Toleration
from renku_data_services.session.cr_shipwright_buildrun import Model as _BuildRun
from renku_data_services.session.cr_shipwright_buildrun import Output as BuildOutput
from renku_data_services.session.cr_shipwright_buildrun import Retention1 as Retention
from renku_data_services.session.cr_shipwright_buildrun import Source as BuildSource
from renku_data_services.session.cr_shipwright_buildrun import Spec as BuildRunSpec
from renku_data_services.session.cr_shipwright_buildrun import Spec1 as BuildSpec
from renku_data_services.session.cr_tekton_taskrun import TaskRunBase as _TaskRunBase


class Metadata(BaseModel):
    """Basic k8s metadata spec."""

    class Config:
        """Do not exclude unknown properties."""

        extra = "allow"

    name: str
    namespace: str | None = None
    labels: dict[str, str] = Field(default_factory=dict)
    annotations: dict[str, str] = Field(default_factory=dict)
    uid: str | None = None
    creationTimestamp: datetime | None = None
    deletionTimestamp: datetime | None = None


class BuildRun(_BuildRun):
    """Shipwright BuildRun."""

    kind: str = "BuildRun"
    apiVersion: str = "shipwright.io/v1beta1"
    # Here we overwrite the default from ASModel because it is too weakly typed
    metadata: Metadata  # type: ignore[assignment]


class GitSource(BuildSource):
    """Git repository as a source for builds."""

    type: str = "Git"
    git: Git


class TaskRun(_TaskRunBase):
    """Tekton TaskRun."""

    metadata: Metadata


class NodeSelector(RootModel[dict[str, str] | None]):
    """A k8s node selector."""

    root: dict[str, str] | None = None


class Tolerations(RootModel[list[Toleration] | None]):
    """A list of k8s tolerations."""

    root: list[Toleration] | None = None


class BuildPlatformOverrides(BaseModel):
    """Configuration overrides for a given target platform.

    Used to validate the builds configuration.
    """

    builderImage: str | None = None
    runImage: str | None = None
    strategyName: str | None = None
    nodeSelector: dict[str, str] | None = None
    tolerations: list[Toleration] | None = None


class BuildPlatformOverridesDict(RootModel[dict[str, BuildPlatformOverrides] | None]):
    """A map of target platforms to configuration overrides.

    Used to validate the builds configuration.
    """

    root: dict[str, BuildPlatformOverrides] | None = None
