openapi: 3.0.2
info:
  title: Renku Data Services API
  description: |
    A service that allows alerts to be sent to users.
  version: v1
servers:
  - url: /api/data
paths:
  /alerts:
    post:
      summary: Send an alert to a user. Requires admin permissions.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlertPost"
      responses:
        "201":
          description: Alert successfully created
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Alert"
      tags:
        - alerts
    get:
      summary: Retrieve all active alerts for the authenticated user.
      responses:
        "200":
          description: A list of active alerts for the authenticated user.
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/AlertList"
      tags:
        - alerts
components:
  schemas:
    Ulid:
      description: ULID identifier
      type: string
      minLength: 26
      maxLength: 26
      pattern: "^[0-7][0-9A-HJKMNP-TV-Z]{25}$" # This is case-insensitive
    Alert:
      description: An alert sent or displayed to a user.
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Ulid"
        title:
          $ref: "#/components/schemas/AlertTitle"
        message:
          $ref: "#/components/schemas/AlertMessage"
        user_id:
          $ref: "#/components/schemas/UserId"
        creation_date:
          type: string
          format: date-time
          description: The date and time when the alert was created.
      required:
        - id
        - title
        - message
        - user_id
    AlertPost:
      description: Data required to create an alert.
      type: object
      properties:
        title:
          $ref: "#/components/schemas/AlertTitle"
        message:
          $ref: "#/components/schemas/AlertMessage"
        user_id:
          $ref: "#/components/schemas/UserId"
      required:
        - title
        - message
        - user_id
    AlertTitle:
      type: string
      description: The title of the alert.
    AlertMessage:
      type: string
      description: The message body of the alert.
    UserId:
      type: string
      description: The ID of the user associated with the alert.
    AlertList:
      type: array
      description: A list of alerts.
      items:
        $ref: "#/components/schemas/Alert"
