# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2025-11-04T13:15:49+00:00

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from pydantic import Field, RootModel
from renku_data_services.notifications.apispec_base import BaseAPISpec


class Alert(BaseAPISpec):
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    title: str = Field(..., description="The title of the alert.")
    message: str = Field(..., description="The message body of the alert.")
    user_id: str = Field(
        ..., description="The ID of the user associated with the alert."
    )
    creation_date: Optional[datetime] = Field(
        None, description="The date and time when the alert was created."
    )


class AlertPost(BaseAPISpec):
    title: str = Field(..., description="The title of the alert.")
    message: str = Field(..., description="The message body of the alert.")
    user_id: str = Field(
        ..., description="The ID of the user associated with the alert."
    )


class AlertList(RootModel[List[Alert]]):
    root: List[Alert] = Field(..., description="A list of alerts.")
