# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2025-11-14T09:05:21+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.notifications.apispec_base import BaseAPISpec


class Status(Enum):
    firing = "firing"
    resolved = "resolved"


class AlertmanagerAlert(BaseAPISpec):
    status: Status = Field(..., description="The status of the alert")
    labels: Dict[str, str] = Field(..., description="Labels associated with the alert")
    annotations: Dict[str, str] = Field(
        ..., description="Annotations associated with the alert"
    )
    startsAt: datetime = Field(..., description="The time when the alert started")
    endsAt: Optional[datetime] = Field(
        None, description="The time when the alert ended"
    )
    generatorURL: Optional[str] = Field(
        None, description="The URL of the generator that created the alert"
    )


class AlertPatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    resolved: Optional[bool] = Field(
        None,
        description="Set to true to mark the alert as resolved. The resolved_at timestamp will be set automatically.",
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class AlertsWebhookAlertmanagerPostResponse(BaseAPISpec):
    message: Optional[str] = Field(None, examples=["Webhook processed successfully"])


class AlertmanagerWebhook(BaseAPISpec):
    version: str = Field(..., description="Alertmanager version")
    groupKey: str = Field(..., description="Unique key for the group of alerts")
    status: Status = Field(..., description="The status of the alerts in this webhook")
    receiver: Optional[str] = Field(
        None, description="The name of the receiver that got the alert"
    )
    groupLabels: Optional[Dict[str, str]] = Field(
        None, description="Labels that are common to all alerts in the group"
    )
    commonLabels: Optional[Dict[str, str]] = Field(
        None, description="Labels that are common to all alerts"
    )
    commonAnnotations: Optional[Dict[str, str]] = None
    externalURL: Optional[str] = Field(
        None, description="The external URL of the Alertmanager"
    )
    alerts: List[AlertmanagerAlert] = Field(..., description="The list of alerts")


class AlertsGetQuery(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    session_name: Optional[str] = Field(
        None,
        description="Renku session name",
        examples=["My Renku Session :)"],
        max_length=99,
        min_length=1,
    )


class Alert(BaseAPISpec):
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    title: str = Field(..., description="The title of the alert.")
    message: str = Field(..., description="The message body of the alert.")
    user_id: str = Field(
        ...,
        description="Keycloak user ID",
        examples=["f74a228b-1790-4276-af5f-25c2424e9b0c"],
        pattern="^[A-Za-z0-9]{1}[A-Za-z0-9-]+$",
    )
    session_name: Optional[str] = Field(
        None,
        description="Renku session name",
        examples=["My Renku Session :)"],
        max_length=99,
        min_length=1,
    )
    creation_date: datetime = Field(
        ..., description="The date and time when the alert was created."
    )
    resolved_at: Optional[datetime] = Field(
        None,
        description="The date and time when the alert was resolved, or null if it is still active.",
    )


class AlertPost(BaseAPISpec):
    title: str = Field(..., description="The title of the alert.")
    message: str = Field(..., description="The message body of the alert.")
    user_id: str = Field(
        ...,
        description="Keycloak user ID",
        examples=["f74a228b-1790-4276-af5f-25c2424e9b0c"],
        pattern="^[A-Za-z0-9]{1}[A-Za-z0-9-]+$",
    )
    session_name: Optional[str] = Field(
        None,
        description="Renku session name",
        examples=["My Renku Session :)"],
        max_length=99,
        min_length=1,
    )


class AlertList(RootModel[List[Alert]]):
    root: List[Alert] = Field(..., description="A list of alerts.")


class AlertsGetParametersQuery(BaseAPISpec):
    params: Optional[AlertsGetQuery] = None
