openapi: 3.0.2
info:
  title: Renku Data Services API
  description: |
    This service is the main backend for Renku. It provides information about users, projects,
    cloud storage, access to compute resources and many other things.
  version: v1
servers:
  - url: /api/data
paths:
  /search/query:
    get:
      summary: Run a search query.
      responses:
        "200":
          description: Search results according to the query.
          headers:
            x-page:
              required: true
              schema:
                type: integer
                format: int32
            x-per-page:
              required: true
              schema:
                type: integer
                format: int32
            x-total:
              required: true
              schema:
                type: integer
                format: int64
            x-total-pages:
              required: true
              schema:
                type: integer
                format: int32
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
  /search/reprovision:
    post:
      summary: Start a new reprovisioning
      description: Only a single reprovisioning is active at any time
      responses:
        "201":
          description: The reprovisioning is/will be started
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reprovisioning"
        "409":
          description: A reprovisioning is already started
        default:
          $ref: "#/components/responses/Error"
      tags:
        - search
    get:
      summary: Return status of reprovisioning
      responses:
        "200":
          description: Status of reprovisioning if there's one in progress
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReprovisioningStatus"
        "404":
          description: There's no active reprovisioning
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        default:
          $ref: "#/components/responses/Error"
      tags:
        - search
    delete:
      summary: Stop an active reprovisioning
      responses:
        "204":
          description: The reprovisioning was stopped or there was no one in progress
        default:
          $ref: "#/components/responses/Error"
      tags:
        - search

components:
  schemas:
    SearchResult:
      description: Results to a search.
      type: object
      properties:

    PageWithTotals:
      type: object
      properties:
        page:
          $ref: "#/components/schemas/PageDef"
        totalResult:
          type: "integer"
          format: "int64"
        totalPages:
          type: "integer"
          format: "int32"
        prevPage:
          type: "integer"
          format: "int32"
        nextPage:
          type: "integer"
          format: "int32"
      required:
        - page
        - totalResult
        - totalPages
    MapEntityTypeCount:
      type: object
      additionalProperties:
        type: "integer"
        format: "int32"
    PageDef:
      type: object
      properties:
        limit:
          type: "integer"
          format: "int32"
        offset:
          type: "integer"
          format: "int32"
      required:
        - limit
        - offset
    FacetData:
      type: object
      properties:
        entityType:
          $ref: "#/components/schemas/MapentityTypeCount"
      required:
        - entityType
    Group:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        namespace:
          type: string
        description:
          type: string
        score:
          type: "number"
          format: "double"
        type:
          type: "string"
          const: "Group"
      required:
        - id
        - name
        - namespace
        - type
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        namespace:
          type: string
        repositories:
          type: array
          items:
            type: string
        visibility:
          $ref: "#/components/schemas/Visibility"
        description:
          type: string
        createdBy:
          $ref: "#/components/schemas/User"
        creationDate:
          type: string
          format: date-time
        keywords:
          type: array
          items:
            type: string
        score:
          type: number
          format: double
        type:
          type: string
          const: "Project"
      required:
        - id
        - name
        - slug
        - visibility
        - creationDate
        - type
    User:
      type: object
      properties:
        id:
          type: string
        namespace:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        score:
          type: number
          format: double
        type:
          type: string
          const: "User"
    UserOrGroup:
      oneOf:
        - $ref: "#/components/schemas/Group"
        - $ref: "#/components/schemas/User"
      discriminator:
        propertyName: "type"
        mapping:
          Group: "#/components/schemas/Group"
          User: "#/components/schemas/User"
    Visibility:
      enum:
        - "private"
        - "public"
    SearchEntity:
      oneOf:
        - $ref: "#/components/schemas/Group"
        - $ref: "#/components/schemas/Project"
        - $ref: "#/components/schemas/User"
      discriminator:
        propertyName: "type"
        mapping:
          Group: "#/components/schemas/Group"
          User: "#/components/schemas/User"
          Project: "#/components/schemas/Project"
    SearchResult:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/SearchEntity"
        facets:
          $ref: "#/components/schemas/FacetData"
        pagingInfo:
          $ref: "#/components/schemas/PageWithTotals"
    Reprovisioning:
      description: A reprovisioning
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Ulid"
        start_date:
          description: The date and time the reprovisioning was started (in UTC and ISO-8601 format)
          type: string
          format: date-time
          example: "2023-11-01T17:32:28Z"
      required:
        - id
        - start_date
    ReprovisioningStatus:
      description: Status of a reprovisioning
      allOf:
      - $ref: "#/components/schemas/Reprovisioning"
    Ulid:
      description: ULID identifier
      type: string
      minLength: 26
      maxLength: 26
      pattern: "^[0-7][0-9A-HJKMNP-TV-Z]{25}$" # This is case-insensitive
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              minimum: 0
              exclusiveMinimum: true
              example: 1404
            detail:
              type: string
              example: A more detailed optional message showing what the problem was
            message:
              type: string
              example: Something went wrong - please try again later
          required:
            - code
            - message
      required:
        - error
  responses:
    Error:
      description: The schema for all 4xx and 5xx responses
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
