# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-03-04T10:36:46+00:00

from __future__ import annotations

from datetime import date
from typing import Optional

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.resource_usage.apispec_base import BaseAPISpec


class ResourceUsageSummary(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    runtime: float
    cost: int


class ResourcePoolLimitPut(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_limit: int
    user_limit: int


class ResourceClassCostPut(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    cost: int = Field(
        ...,
        description="The cost of a resource class is an integer that specifies\nthe effective cost of a session using this class running\nfor one hour.\n",
    )


class ResourceClassCost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource_pool_id: int
    resource_class_id: int
    cost: int


class ResourcePoolLimits(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    pool_id: int
    total_limit: int
    user_limit: int


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: Optional[str] = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class Ulid(RootModel[str]):
    root: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )


class ResourcePoolsResourcePoolIdUsageGetParametersQuery(BaseAPISpec):
    start_date: Optional[date] = None
    end_date: Optional[date] = None


class ResourcePoolUsage(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    total_usage: ResourceUsageSummary
    user_usage: ResourceUsageSummary
    pool_limits: ResourcePoolLimits
