# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-09-23T12:52:51+00:00

from __future__ import annotations

from typing import Any

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.secrets.apispec_base import BaseAPISpec


class Version(BaseAPISpec):
    version: str


class Ulid(RootModel[str]):
    root: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class K8sSecret(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(
        ...,
        description="The name of the k8s secret to create",
        examples=["john-doe-session-57-secret"],
    )
    namespace: str = Field(
        ..., description="The namespace of the k8s secret to create", examples=["renku"]
    )
    secret_ids: list[Ulid] = Field(
        ..., description="The ids of the secrets to include", min_length=1
    )
    owner_references: list[dict[str, str]] = Field(
        ...,
        description="The resource in K8s that owns this secret",
        examples=[
            [
                {
                    "apiVersion": "amalthea.dev/v1alpha1",
                    "kind": "JupyterServer",
                    "name": "renku-1234",
                    "uid": "c9328118-8d32-41b4-b9bd-1437880c95a2",
                }
            ]
        ],
    )
    key_mapping: dict[str, str | list[str]] | None = None
    cluster_id: str | None = Field(
        None,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )


class DataConnectorWithSecrets(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    remote_name: str
    remote_path: str | None = None
    config: dict[str, Any]
    secrets: dict[str, str | list[str]] | None = None


class DataConnectorsK8sSecret(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(
        ...,
        description="The name of the k8s secret to create",
        examples=["john-doe-session-57-secret"],
    )
    namespace: str = Field(
        ..., description="The namespace of the k8s secret to create", examples=["renku"]
    )
    data_connectors: list[DataConnectorWithSecrets] = Field(
        ...,
        description="The data connector configurations and optionally secrets to create",
        min_length=1,
    )
    combined_remote_name: str = Field(
        ...,
        description="The name of the remote where the data connectors are combined",
        examples=["__combined__"],
    )
    owner_references: list[dict[str, str]] = Field(
        ...,
        description="The resource in K8s that owns this secret",
        examples=[
            [
                {
                    "apiVersion": "amalthea.dev/v1alpha1",
                    "kind": "JupyterServer",
                    "name": "renku-1234",
                    "uid": "c9328118-8d32-41b4-b9bd-1437880c95a2",
                }
            ]
        ],
    )
    cluster_id: str | None = Field(
        None,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
