"""Add tolerations and node affinities

Revision ID: 5949d0d930e8
Revises: 95ce5418d4d9
Create Date: 2023-09-10 09:06:21.641537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5949d0d930e8"
down_revision = "95ce5418d4d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "node_affinities",
        sa.Column("key", sa.String(length=63), nullable=False),
        sa.Column("resource_class_id", sa.Integer(), nullable=False),
        sa.Column("required_during_scheduling", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_class_id"],
            ["resource_pools.resource_classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="resource_pools",
    )
    op.create_table(
        "tolerations",
        sa.Column("key", sa.String(length=63), nullable=False),
        sa.Column("resource_class_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["resource_class_id"],
            ["resource_pools.resource_classes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="resource_pools",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tolerations", schema="resource_pools")
    op.drop_table("node_affinities", schema="resource_pools")
    # ### end Alembic commands ###
