"""create_tables

Revision ID: 10e6b7f37bad
Revises:
Create Date: 2023-08-17 15:12:03.550786

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "10e6b7f37bad"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_storage",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("storage_type", sa.String(length=20), nullable=False),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("source_path", sa.String(), nullable=False),
        sa.Column("target_path", sa.String(), nullable=False),
        sa.Column("storage_id", sa.String(length=26), nullable=False),
        sa.PrimaryKeyConstraint("storage_id"),
        schema="storage",
    )
    op.create_index(
        op.f("ix_storage_cloud_storage_project_id"), "cloud_storage", ["project_id"], unique=False, schema="storage"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_storage_cloud_storage_project_id"), table_name="cloud_storage", schema="storage")
    op.drop_table("cloud_storage", schema="storage")
    # ### end Alembic commands ###
