"""remove private field

Revision ID: 61a4d72981cf
Revises: c1960188d4cc
Create Date: 2023-12-01 16:53:11.048206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "61a4d72981cf"
down_revision = "c1960188d4cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cloud_storage", "private", schema="storage")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cloud_storage", sa.Column("private", sa.BOOLEAN(), autoincrement=False, nullable=False), schema="storage"
    )
    # ### end Alembic commands ###
