"""Create tables

Revision ID: 8f5adec034fb
Revises:
Create Date: 2023-07-26 17:06:34.455488

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8f5adec034fb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cloud_storage",
        sa.Column("git_url", sa.String(), nullable=False),
        sa.Column("storage_type", sa.String(length=20), nullable=False),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("storage_id", sa.String(length=26), nullable=False),
        sa.PrimaryKeyConstraint("storage_id"),
    )
    op.create_index(op.f("ix_cloud_storage_git_url"), "cloud_storage", ["git_url"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cloud_storage_git_url"), table_name="cloud_storage")
    op.drop_table("cloud_storage")
    # ### end Alembic commands ###
