"""Add user preferences

Revision ID: 6eccd7d4e3ed
Revises:
Create Date: 2023-11-10 11:43:46.237517

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision = "6eccd7d4e3ed"
down_revision: str | None = None
branch_labels = ("user_preferences",)
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # this migration in the past created a user_preferences table in the user_preferences schema
    # this table is now in the `users` schema, so we don't want to create it here (it's done in a new migration)
    # If this migration already ran in the past, it doesn't matter
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_preferences", schema="user_preferences")
    # ### end Alembic commands ###
