version: 2
updates:
- package-ecosystem: "pip"
  directories:
    - "/"
    - "/projects/renku_data_service"
    - "/projects/background_jobs"
    - "/projects/secrets_storage"
  schedule:
    interval: "weekly"
    day: "sunday"
  open-pull-requests-limit: 5
  groups:
    poetry:
      patterns:
        - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
