version: '3.8'

services:
  # crc:
  #   build:
  #     context: ..
  #     dockerfile: projects/renku_crc/Dockerfile

  #   volumes:
  #     - ../..:/workspaces:cached

  #   # Overrides default command so things don't shut down after the process ends.
  #   command: sleep infinity

  #   # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
  #   network_mode: service:db

  #   # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
  #   # (Adding the "ports" property to this file will not forward from a Codespace.)

  storage:
    build:
      context: ..
      dockerfile: projects/renku_storage/Dockerfile
      args:
        - USER_UID=$USER_UID
        - USER_GID=$USER_GID

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    environment:
      DB_USER: renku
      DB_NAME: renku
      DB_PASSWORD: renku
      DB_HOST: db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: renku
      POSTGRES_DB: renku
      POSTGRES_PASSWORD: renku

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
