version: '3.8'

services:
  data_service:
    image: "mcr.microsoft.com/devcontainers/python:3.13-bookworm"
    volumes:
      - ../:/workspace:cached
      - .poetry_cache/:/poetry_cache:delegated
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: sleep infinity
    environment:
      DB_USER: renku
      DB_NAME: renku
      DB_PASSWORD: renku
      DB_HOST: 127.0.0.1
      CORS_ALLOW_ALL_ORIGINS: "true"
      ALEMBIC_CONFIG: /workspace/components/renku_data_services/migrations/alembic.ini
      AUTHZ_DB_HOST: 127.0.0.1
      AUTHZ_DB_GRPC_PORT: "50051"
      AUTHZ_DB_KEY: renku
      AUTHZ_DB_NO_TLS_CONNECTION: "true"
      ZED_ENDPOINT: 127.0.0.1:50051
      ZED_TOKEN: renku
      ZED_INSECURE: "true"
      POETRY_CACHE_DIR: "/poetry_cache"
      NB_SERVER_OPTIONS__DEFAULTS_PATH: /workspace/server_defaults.json
      NB_SERVER_OPTIONS__UI_CHOICES_PATH: /workspace/server_options.json
      KUBECONFIG: "/workspace/.k3d-config.yaml"
      SOLR_URL: "http://127.0.0.1:8983"
      SOLR_CORE: "renku-search-dev"
    network_mode: service:db
    depends_on:
      - db
      - authz

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./generate_ulid_func.sql
        target: /docker-entrypoint-initdb.d/generate_ulid_func.sql
    environment:
      POSTGRES_USER: renku
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: renku
    ports:
      - "8000:8000"
      - "5432:5432"
      - "8080:8080"
      - "5678:5678"
      - "50051:50051"
      - "8888:80"

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON_URL: http://localhost:8000/api/data/spec.json
      PORT: "8080"
    network_mode: service:db

  authz:
    image: authzed/spicedb:latest-debug
    restart: unless-stopped
    depends_on:
      - db
    environment:
      SPICEDB_GRPC_PRESHARED_KEY: renku
      SPICEDB_DATASTORE_CONN_URI: "postgres://renku:renku@127.0.0.1:5432/postgres"
    network_mode: service:db
    command:
      - serve

  solr:
    image: solr:9
    restart: unless-stopped
    volumes:
      - solr_data:/var/solr
    command:
      - bash
      - -c
      - 'precreate-core renku-search-dev; exec solr -f -Dsolr.modules=analysis-extras'

volumes:
  postgres-data:
  solr_data:
