version: '3.8'

services:
  data_service:
    build:
      context: ..
      dockerfile: projects/renku_data_service/Dockerfile
      args:
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    environment:
      DB_USER: renku
      DB_NAME: renku
      DB_PASSWORD: renku
      DB_HOST: db
      CORS_ALLOW_ALL_ORIGINS: "true"
      ALEMBIC_CONFIG: /workspaces/renku-data-services/components/renku_data_services/migrations/alembic.ini

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: renku
      POSTGRES_DB: renku
      POSTGRES_PASSWORD: renku

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  swagger:
    image: swaggerapi/swagger-ui
    network_mode: service:db
    environment:
      SWAGGER_JSON_URL: http://localhost:8000/api/data/spec.json
      PORT: "8080"

volumes:
  postgres-data:
