# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-09-16T15:18:04+00:00

from __future__ import annotations

from datetime import date, time
from enum import StrEnum

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.capacity_reservation.apispec_base import BaseAPISpec


class RecurrenceType(StrEnum):
    once = "once"
    daily = "daily"
    weekly = "weekly"


class ScaleDownBehavior(StrEnum):
    maintain = "maintain"
    reduce = "reduce"
    none = "none"


class ScheduleEntry(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    day_of_week: int = Field(..., examples=[1], ge=1, le=7)
    start_time: time = Field(..., examples=["08:00:00"])
    end_time: time = Field(..., examples=["18:00:00"])


class RecurrenceConfig(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: RecurrenceType
    start_date: date = Field(..., examples=["2026-01-15"])
    end_date: date = Field(..., examples=["2026-06-15"])
    schedule: list[ScheduleEntry] = Field([], validate_default=True)


class ProvisioningConfig(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    placeholder_count: int = Field(..., examples=[10], ge=1)
    lead_time_minutes: int = Field(..., examples=[30], ge=0, le=180)
    scale_down_behavior: ScaleDownBehavior


class CapacityReservationPost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., examples=["Monday Morning Course"], max_length=40)
    resource_class_id: int = Field(..., examples=[42])
    resource_pool_id: int | None = Field(None, examples=[7])
    project_template_id: str | None = Field(
        None,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    recurrence: RecurrenceConfig
    provisioning: ProvisioningConfig


class CapacityReservation(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    name: str = Field(..., examples=["Monday Morning Course"], max_length=40)
    resource_class_id: int = Field(..., examples=[42])
    resource_pool_id: int | None = Field(None, examples=[7])
    project_template_id: str | None = Field(
        None, examples=["01ARZ3NDEKTSV4RRFFQ69G5FAV"]
    )
    recurrence: RecurrenceConfig
    provisioning: ProvisioningConfig


class CapacityReservationList(RootModel[list[CapacityReservation]]):
    root: list[CapacityReservation]


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error
