# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-04-09T12:11:25+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import ConfigDict, Field
from renku_data_services.authn.api.apispec_base import BaseAPISpec


class PostTokenResponse(BaseAPISpec):
    model_config = ConfigDict(
        extra="allow",
    )
    access_token: str
    token_type: str
    expires_in: int
    refresh_token: str
    refresh_expires_in: Optional[int] = None
    scope: Optional[str] = None


class PostTokenGrantType(Enum):
    refresh_token = "refresh_token"


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: Optional[str] = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class PostTokenRequest(BaseAPISpec):
    model_config = ConfigDict(
        extra="allow",
    )
    grant_type: PostTokenGrantType
    refresh_token: str
