# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-07-20T11:41:32+00:00

from __future__ import annotations

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.persisted_logs.apispec_base import BaseAPISpec


class PersistedSessionLogs(BaseAPISpec):
    model_config = ConfigDict(
        extra="allow",
    )


class SessionRuns(BaseAPISpec):
    model_config = ConfigDict(
        extra="allow",
    )


class Ulid(RootModel[str]):
    root: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error
