# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2026-07-21T08:24:35+00:00

from __future__ import annotations

from pydantic import Field, RootModel
from renku_data_services.persisted_logs.apispec_base import BaseAPISpec


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: str | None = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )
    trace_id: str | None = Field(
        None,
        description="Sentry trace ID for linking to corresponding log entries",
        examples=["ac93950e9e114a55c67fb8e5ef519bbe"],
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class SessionRun(BaseAPISpec):
    id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    launch_id: str
    launcher_id: str = Field(
        ...,
        description="ULID identifier",
        max_length=26,
        min_length=26,
        pattern="^[0-7][0-9A-HJKMNP-TV-Z]{25}$",
    )
    submission_id: str | None = None


class PersistedLogLines(BaseAPISpec):
    timestamp: str = Field(
        ..., description="UNIX timestamp in nanoseconds", pattern="[0-9]+"
    )
    log_line: str


class SessionRuns(RootModel[list[SessionRun]]):
    root: list[SessionRun] = Field(..., description="A list of session runs")


class SessionRunLogsItem(BaseAPISpec):
    container: str
    logs: PersistedLogLines


class PersistedSessionLogs(BaseAPISpec):
    run: SessionRun
    logs: list[SessionRunLogsItem] = Field(
        ..., description="Logs of a session run, organized by pod container."
    )
