# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2025-08-22T13:48:29+00:00

from __future__ import annotations

from typing import Any, List, Literal, Optional, Union

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.platform.apispec_base import BaseAPISpec


class RedirectTargetUrl(BaseAPISpec):
    url: str = Field(..., description="The protocol-relative URL to redirect to")
    targetType: Literal["Url"] = "Url"


class PaginationRequest(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    page: int = Field(1, description="Result's page number starting from 1", ge=1)
    per_page: int = Field(
        20, description="The number of results per page", ge=1, le=100
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class PlatformConfig(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    etag: str = Field(
        ..., description="Entity Tag", examples=["9EE498F9D565D0C41E511377425F32F3"]
    )
    incident_banner: str = Field(
        ...,
        description="The contents of the incident banner.\nThis value accepts content written using Markdown.\n",
        examples=["RenkuLab is experiencing issues, some features may be unavailable."],
    )


class PlatformConfigPatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    incident_banner: Optional[str] = Field(
        None,
        description="The contents of the incident banner.\nThis value accepts content written using Markdown.\n",
        examples=["RenkuLab is experiencing issues, some features may be unavailable."],
    )


class RedirectTargetEntity(BaseAPISpec):
    namespace: Any = Field(..., description="The namespace of the Renku entity")
    slug: Any = Field(..., description="The slug of the Renku entity")
    entity_type: str = Field(..., description="The Renku entity type")
    targetType: Literal["Entity"] = "Entity"


class RedirectInfosGetQuery(PaginationRequest):
    pass


class RedirectInfoPost1(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_url: str = Field(..., description="The protocol-relative URL to redirect")
    namespace: Any = Field(..., description="The namespace of the Renku entity")
    slug: Any = Field(..., description="The slug of the Renku entity")
    entity_type: str = Field(..., description="The Renku entity type")
    target_url: Optional[str] = Field(
        None, description="The protocol-relative URL to redirect to"
    )


class RedirectInfoPost2(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_url: str = Field(..., description="The protocol-relative URL to redirect")
    namespace: Optional[Any] = Field(
        None, description="The namespace of the Renku entity"
    )
    slug: Optional[Any] = Field(None, description="The slug of the Renku entity")
    entity_type: Optional[str] = Field(None, description="The Renku entity type")
    target_url: str = Field(..., description="The protocol-relative URL to redirect to")


class RedirectInfoPost(RootModel[Union[RedirectInfoPost1, RedirectInfoPost2]]):
    root: Union[RedirectInfoPost1, RedirectInfoPost2] = Field(
        ..., description="Schema for creating a new redirect info"
    )


class PlatformRedirectsGetParametersQuery(BaseAPISpec):
    params: Optional[RedirectInfosGetQuery] = None


class RedirectInfo(BaseAPISpec):
    source_url: str = Field(..., description="The protocol-relative URL to redirect")
    target: Union[RedirectTargetEntity, RedirectTargetUrl] = Field(
        ..., description="The target of the redirect", discriminator="targetType"
    )


class RedirectInfoList(RootModel[List[RedirectInfo]]):
    root: List[RedirectInfo] = Field(..., description="A list of redirect info objects")
