# generated by datamodel-codegen:
#   filename:  api.spec.yaml
#   timestamp: 2025-08-26T09:27:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import ConfigDict, Field, RootModel
from renku_data_services.platform.apispec_base import BaseAPISpec


class RedirectPlan(BaseAPISpec):
    source_url: str = Field(..., description="The protocol-relative URL to redirect")
    target_url: str = Field(..., description="The protocol-relative URL to redirect to")


class RedirectPlanPost(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_url: str = Field(..., description="The protocol-relative URL to redirect")
    target_url: str = Field(..., description="The protocol-relative URL to redirect to")


class PaginationRequest(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    page: int = Field(1, description="Result's page number starting from 1", ge=1)
    per_page: int = Field(
        20, description="The number of results per page", ge=1, le=100
    )


class Error(BaseAPISpec):
    code: int = Field(..., examples=[1404], gt=0)
    detail: Optional[str] = Field(
        None, examples=["A more detailed optional message showing what the problem was"]
    )
    message: str = Field(
        ..., examples=["Something went wrong - please try again later"]
    )


class ErrorResponse(BaseAPISpec):
    error: Error


class SlugResponse(RootModel[str]):
    root: str = Field(
        ...,
        description="A command-line/url friendly name for a namespace",
        examples=["a-slug-example"],
        min_length=1,
    )


class PlatformConfig(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    etag: str = Field(
        ..., description="Entity Tag", examples=["9EE498F9D565D0C41E511377425F32F3"]
    )
    incident_banner: str = Field(
        ...,
        description="The contents of the incident banner.\nThis value accepts content written using Markdown.\n",
        examples=["RenkuLab is experiencing issues, some features may be unavailable."],
    )


class PlatformConfigPatch(BaseAPISpec):
    model_config = ConfigDict(
        extra="forbid",
    )
    incident_banner: Optional[str] = Field(
        None,
        description="The contents of the incident banner.\nThis value accepts content written using Markdown.\n",
        examples=["RenkuLab is experiencing issues, some features may be unavailable."],
    )


class RedirectPlanList(RootModel[List[RedirectPlan]]):
    root: List[RedirectPlan] = Field(..., description="A list of redirect info objects")


class RedirectPlansGetQuery(PaginationRequest):
    pass


class PlatformRedirectsGetParametersQuery(BaseAPISpec):
    params: Optional[RedirectPlansGetQuery] = None
