---
openapi: 3.0.2
info:
  title: Renku cloud storage services
  description: |
    Services that provide information about data, users and compute resources. All errors
    have the same format as the schema called ErrorResponse.
  version: v1
servers:
  - url: /api/storage
  - url: /ui-server/api/storage
paths:
  /storage:
    post:
      summary: create a new cloud storage for a project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "#/components/schemas/CloudStorage"
                - $ref: "#/components/schemas/CloudStorageUrl"
      responses:
        "201":
          description: The cloud storage entry was created
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/CloudStorage"
components:
  schemas:
    CloudStorageUrl:
      type: object
      properties:
        git_url:
          type: string
        storage_url:
          type: string
      required:
        - git_url
        - storage_url
      example:
        git_url: https://renkulab.io/gitlab/rok.roskar/test
        storage_url: s3://giab
    CloudStorage:
      type: object
      properties:
        git_url:
          type: string
        type:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              minimum: 0
              exclusiveMinimum: true
              example: 1404
            detail:
              type: string
              example: "A more detailed optional message showing what the problem was"
            message:
              type: string
              example: "Something went wrong - please try again later"
          required: ["code", "message"]
      required: ["error"]

  responses:
    Error:
      description: The schema for all 4xx and 5xx responses
      content:
        "application/json":
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  securitySchemes:
    oidc:
      type: openIdConnect
      openIdConnectUrl: /auth/realms/Renku/.well-known/openid-configuration
security:
  - oidc:
      - openid
