"""generate tables

Revision ID: 19d787dd68c0
Revises:
Create Date: 2023-02-12 01:11:59.234911

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "19d787dd68c0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(26), nullable=False),
        sa.Column("name", sa.String(99), nullable=False),
        sa.Column("created_by_id", sa.String(99), nullable=False),
        sa.Column("creation_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("environment_id", sa.String(500), nullable=False),  # TODO: This should be 26
        sa.Column("description", sa.String(500), nullable=True),
        sa.Column("project_id", sa.String(26), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="sessions",
    )
    op.create_index(
        op.f("ix_sessions_sessions_environment_id"),
        "sessions",
        ["environment_id"],
        unique=False,
        schema="sessions",
    )
    op.create_index(
        op.f("ix_sessions_sessions_project_id"),
        "sessions",
        ["project_id"],
        unique=False,
        schema="sessions",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_sessions_project_id"), table_name="sessions", schema="sessions")
    op.drop_index(op.f("ix_sessions_sessions_environment_id"), table_name="sessions", schema="sessions")
    op.drop_table("sessions", schema="sessions")
    # ### end Alembic commands ###
